export const stacks = [
    { value: '0', label: '.NET' },
    { value: '1', label: 'ASP.NET' },
    { value: '2', label: 'Angular' },
    { value: '3', label: 'AngularJS' },
    { value: '4', label: 'Apache Spark' },
    { value: '5', label: 'Blazor' },
    { value: '6', label: 'C' },
    { value: '7', label: 'C#' },
    { value: '8', label: 'C++' },
    { value: '9', label: 'Dart' },
    { value: '10', label: 'Django' },
    { value: '11', label: 'Electron' },
    { value: '12', label: 'Express' },
    { value: '13', label: 'Flask' },
    { value: '14', label: 'Flutter' },
    { value: '15', label: 'Go' },
    { value: '16', label: 'HTML/CSS' },
    { value: '17', label: 'Java' },
    { value: '18', label: 'JavaScript' },
    { value: '19', label: 'jQuery' },
    { value: '20', label: 'Keras' },
    { value: '21', label: 'Kotlin' },
    { value: '22', label: 'Laravel' },
    { value: '23', label: 'Lua' },
    { value: '24', label: 'NestJS' },
    { value: '25', label: 'Next.js' },
    { value: '26', label: 'Node.js' },
    { value: '27', label: 'OpenGL' },
    { value: '28', label: 'Opencv' },
    { value: '29', label: 'PHP' },
    { value: '30', label: 'Pandas' },
    { value: '31', label: 'PyTorch' },
    { value: '32', label: 'Python' },
    { value: '33', label: 'Qt' },
    { value: '34', label: 'R' },
    { value: '35', label: 'RabbitMQ' },
    { value: '36', label: 'React' },
    { value: '37', label: 'React Native' },
    { value: '38', label: 'Ruby' },
    { value: '39', label: 'Ruby on Rails' },
    { value: '40', label: 'Rust' },
    { value: '41', label: 'scikit-Learn' },
    { value: '42', label: 'SpringBoot' },
    { value: '43', label: 'Svelte' },
    { value: '44', label: 'Swift' },
    { value: '45', label: 'SwiftUI' },
    { value: '46', label: 'TensorFlow' },
    { value: '47', label: 'Torch' },
    { value: '48', label: 'TypeScript' },
    { value: '49', label: 'Vue.js' },
];
