export const testdata = [
  {'user_id': 1000, 'user_stacks': ['Ruby', 'Kotlin', 'PyTorch', 'Rust', 'Pandas', 'React Native', 'OpenGL', 'C#', 'Angular', 'Vue.js']},
  {'user_id': 1001, 'user_stacks': ['SpringBoot', 'React Native', 'Rust', 'HTML/CSS', 'NestJS', 'Torch', 'PHP']},
  {'user_id': 1002, 'user_stacks': ['NestJS', 'SwiftUI', 'OpenGL', 'Java', 'jQuery']},
  {'user_id': 1003, 'user_stacks': ['SpringBoot', 'Blazor', 'OpenGL', 'Go', 'Vue.js', 'HTML/CSS', 'scikit-Learn', '.NET', 'NestJS']},
  {'user_id': 1004, 'user_stacks': ['Express', 'SwiftUI', 'scikit-Learn']},
  {'user_id': 1005, 'user_stacks': ['C++', 'scikit-Learn', 'Opencv', 'Next.js', 'OpenGL', 'Apache Spark', 'HTML/CSS', 'Dart']},
  {'user_id': 1006, 'user_stacks': ['OpenGL', 'Laravel', 'NestJS', 'Blazor', 'Angular', 'Python', 'Flutter', 'Pandas', 'ASP.NET', 'Ruby on Rails']},
  {'user_id': 1007, 'user_stacks': ['React', 'Kotlin', 'Next.js', 'C#', 'C++', 'AngularJS', 'Svelte', 'Node.js', 'HTML/CSS']},
  {'user_id': 1008, 'user_stacks': ['Lua', 'PyTorch', 'TensorFlow', 'Ruby on Rails', 'Vue.js', 'React Native', 'NestJS', 'Go', 'Ruby', 'ASP.NET']},
  {'user_id': 1009, 'user_stacks': ['Svelte', 'jQuery']},
  {'user_id': 1010, 'user_stacks': ['React', 'AngularJS']},
  {'user_id': 1011, 'user_stacks': ['Dart', 'Angular', 'Node.js', 'Electron', 'Kotlin', 'Lua', 'Swift', 'jQuery']},
  {'user_id': 1012, 'user_stacks': ['ASP.NET', 'Apache Spark', 'NestJS', 'Go', 'PyTorch', 'Node.js']},
  {'user_id': 1013, 'user_stacks': ['Dart', 'Flutter', 'TypeScript', 'NestJS', '.NET']},
  {'user_id': 1014, 'user_stacks': ['Node.js', 'Opencv', 'Rust']},
  {'user_id': 1015, 'user_stacks': ['Django', 'AngularJS', 'Node.js']},
  {'user_id': 1016, 'user_stacks': ['Ruby', 'Vue.js', 'React Native', 'Kotlin', 'Blazor', 'Qt', 'PHP', 'Node.js', 'Ruby on Rails']},
  {'user_id': 1017, 'user_stacks': ['scikit-Learn', 'HTML/CSS', 'AngularJS', 'Electron']},
  {'user_id': 1018, 'user_stacks': ['Node.js', 'Laravel', 'SwiftUI', 'HTML/CSS', 'PyTorch']},
  {'user_id': 1019, 'user_stacks': ['JavaScript', 'React Native', 'PyTorch']},
  {'user_id': 1020, 'user_stacks': ['JavaScript', 'Express', 'Svelte', 'SwiftUI', 'Next.js', 'scikit-Learn', 'Flask', 'C++', 'React']},
  {'user_id': 1021, 'user_stacks': ['Flask', 'Java', 'Next.js', 'Keras', 'PyTorch', 'Pandas', 'Django', 'HTML/CSS']},
  {'user_id': 1022, 'user_stacks': ['Express', 'RabbitMQ', 'HTML/CSS', 'C#', 'Blazor', 'Ruby on Rails', 'Ruby', 'TypeScript', 'Pandas']},
  {'user_id': 1023, 'user_stacks': ['AngularJS', 'TypeScript', 'Django', 'Ruby', 'Python', 'React Native']},
  {'user_id': 1024, 'user_stacks': ['React Native', 'C++', 'TensorFlow', 'Kotlin', 'Opencv', 'jQuery', 'Svelte', 'Node.js', 'Blazor']},
  {'user_id': 1025, 'user_stacks': ['ASP.NET']},
  {'user_id': 1026, 'user_stacks': ['Flutter', 'jQuery', '.NET', 'PyTorch', 'React', 'NestJS', 'TensorFlow']},
  {'user_id': 1027, 'user_stacks': ['Dart', 'Ruby', 'Kotlin', 'C++', 'Express', 'Qt', 'Node.js', 'Go', 'AngularJS', 'C']},
  {'user_id': 1028, 'user_stacks': ['RabbitMQ', 'jQuery', 'Pandas', 'TensorFlow', 'Node.js', 'C#', 'Vue.js', '.NET', 'Java']},
  {'user_id': 1029, 'user_stacks': ['C#', '.NET', 'HTML/CSS', 'Angular', 'Svelte', 'PyTorch', 'Blazor']},
  {'user_id': 1030, 'user_stacks': ['Laravel', 'TypeScript', 'Flutter', 'HTML/CSS', 'React Native']},
  {'user_id': 1031, 'user_stacks': ['JavaScript', 'React', 'C++']},
  {'user_id': 1032, 'user_stacks': ['React', 'Express', 'Apache Spark', 'AngularJS', '.NET']},
  {'user_id': 1033, 'user_stacks': ['Blazor']},
  {'user_id': 1034, 'user_stacks': ['Dart', 'RabbitMQ', 'Electron', '.NET', 'Rust', 'C']},
  {'user_id': 1035, 'user_stacks': ['Flask', 'Next.js', 'Vue.js', 'Flutter']},
  {'user_id': 1036, 'user_stacks': ['R', 'Java', 'Kotlin', 'Go', 'NestJS', 'React', 'Express', 'ASP.NET']},
  {'user_id': 1037, 'user_stacks': ['Blazor', 'Go', 'Keras', 'Dart', 'OpenGL', 'NestJS', 'R', 'AngularJS']},
  {'user_id': 1038, 'user_stacks': ['Qt', 'PyTorch', 'SwiftUI', 'Kotlin', 'Java', 'Blazor', 'Next.js']},
  {'user_id': 1039, 'user_stacks': ['R', 'React', 'scikit-Learn', 'SpringBoot', 'C', 'Pandas', 'Opencv', 'Electron', 'Python']},
  {'user_id': 1040, 'user_stacks': ['Flask']},
  {'user_id': 1041, 'user_stacks': ['Express', 'R', 'Vue.js']},
  {'user_id': 1042, 'user_stacks': ['SpringBoot', 'Blazor', 'Python', 'PHP', 'HTML/CSS', 'AngularJS', 'PyTorch', 'TensorFlow', 'R']},
  {'user_id': 1043, 'user_stacks': ['Dart', 'C#', 'Express', 'C', 'Svelte', 'R', 'React Native', 'React']},
  {'user_id': 1044, 'user_stacks': ['Svelte', 'Node.js', 'React', 'Rust']},
  {'user_id': 1045, 'user_stacks': ['Vue.js', 'Kotlin', 'OpenGL', 'TensorFlow', 'NestJS', 'Qt', 'Django', 'Flutter', 'SpringBoot', 'Svelte']},
  {'user_id': 1046, 'user_stacks': ['Ruby on Rails', 'TypeScript', 'Vue.js']},
  {'user_id': 1047, 'user_stacks': ['Laravel', 'Blazor', 'Next.js']},
  {'user_id': 1048, 'user_stacks': ['Go', 'React Native']},
  {'user_id': 1049, 'user_stacks': ['.NET', 'Kotlin', 'Go', 'React', 'Torch', 'Blazor', 'Django', 'Rust', 'Svelte']},
  {'user_id': 1050, 'user_stacks': ['C++', 'HTML/CSS', '.NET', 'Electron']},
  {'user_id': 1051, 'user_stacks': ['Flutter', 'ASP.NET', 'scikit-Learn']},
  {'user_id': 1052, 'user_stacks': ['React Native']},
  {'user_id': 1053, 'user_stacks': ['PyTorch', 'Svelte', '.NET', 'Python']},
  {'user_id': 1054, 'user_stacks': ['Qt', 'Ruby on Rails', 'TypeScript', 'Ruby', 'C', 'Swift', 'Keras', 'TensorFlow', 'JavaScript', 'ASP.NET']},
  {'user_id': 1055, 'user_stacks': ['Rust', 'R', 'SpringBoot']},
  {'user_id': 1056, 'user_stacks': ['TypeScript', 'SwiftUI', 'Node.js', 'Lua', 'Laravel', 'SpringBoot', '.NET']},
  {'user_id': 1057, 'user_stacks': ['SwiftUI', 'R']},
  {'user_id': 1058, 'user_stacks': ['HTML/CSS', 'Opencv', 'Blazor']},
  {'user_id': 1059, 'user_stacks': ['Qt']},
  {'user_id': 1060, 'user_stacks': ['Ruby', 'TypeScript', 'TensorFlow', 'scikit-Learn', 'Blazor']},
  {'user_id': 1061, 'user_stacks': ['HTML/CSS', 'Go', 'Angular', 'SwiftUI', 'Python', 'C++', 'AngularJS', 'Node.js', 'Laravel', 'C#']},
  {'user_id': 1062, 'user_stacks': ['Pandas', 'Java', 'C#', 'Flutter', 'C']},
  {'user_id': 1063, 'user_stacks': ['C#', 'SpringBoot', 'PyTorch', 'Vue.js']},
  {'user_id': 1064, 'user_stacks': ['Svelte', 'Ruby on Rails', 'Flutter', 'Lua', 'SpringBoot', 'TensorFlow', 'Qt', 'Opencv', 'Electron', 'Flask']},
  {'user_id': 1065, 'user_stacks': ['Flask', 'OpenGL', 'Opencv', 'Rust', 'Dart', 'SwiftUI', 'R']},
  {'user_id': 1066, 'user_stacks': ['C++', 'Next.js', 'Express', 'Apache Spark', 'React', 'AngularJS', 'Angular']},
  {'user_id': 1067, 'user_stacks': ['OpenGL', 'Vue.js', 'PyTorch', 'Python', 'C#', 'C++', 'ASP.NET']},
  {'user_id': 1068, 'user_stacks': ['Lua', 'Electron', 'Opencv', 'Blazor', 'ASP.NET', 'React', 'OpenGL', 'R']},
  {'user_id': 1069, 'user_stacks': ['Angular', 'Lua', 'SpringBoot', 'R', 'ASP.NET', 'Next.js']},
  {'user_id': 1070, 'user_stacks': ['Blazor', 'Keras', 'Opencv', 'PyTorch', 'Flutter', 'Rust', 'Torch', 'scikit-Learn']},
  {'user_id': 1071, 'user_stacks': ['JavaScript']},
  {'user_id': 1072, 'user_stacks': ['NestJS', 'PyTorch']},
  {'user_id': 1073, 'user_stacks': ['ASP.NET', 'Dart', 'Java', 'C#', 'RabbitMQ', 'C++', 'Blazor', 'AngularJS', 'Flask', 'Go']},
  {'user_id': 1074, 'user_stacks': ['Blazor', 'Rust']},
  {'user_id': 1075, 'user_stacks': ['Kotlin', 'Java', 'C#', 'TensorFlow', 'Svelte', 'Apache Spark', 'Flutter', 'HTML/CSS']},
  {'user_id': 1076, 'user_stacks': ['Ruby on Rails', 'Svelte']},
  {'user_id': 1077, 'user_stacks': ['AngularJS', 'Opencv', 'Dart', 'SpringBoot', 'Angular', 'PHP', 'SwiftUI', 'React Native', 'Swift', '.NET']},
  {'user_id': 1078, 'user_stacks': ['Kotlin', 'PyTorch', 'Python', 'Flutter', 'TensorFlow', '.NET', 'React Native', 'Opencv', 'HTML/CSS']},
  {'user_id': 1079, 'user_stacks': ['Electron']},
  {'user_id': 1080, 'user_stacks': ['NestJS']},
  {'user_id': 1081, 'user_stacks': ['Dart', 'PyTorch', 'OpenGL', 'RabbitMQ', 'Opencv', 'Vue.js', 'Rust', 'Node.js', 'Keras']},
  {'user_id': 1082, 'user_stacks': ['Go', 'scikit-Learn', 'RabbitMQ', 'Express']},
  {'user_id': 1083, 'user_stacks': ['AngularJS', 'Angular', 'Lua', 'Flutter', 'ASP.NET', 'Rust', 'Electron', 'TypeScript', 'Pandas', 'Torch']},
  {'user_id': 1084, 'user_stacks': ['Electron', 'R', 'Vue.js', 'C++']},
  {'user_id': 1085, 'user_stacks': ['.NET']},
  {'user_id': 1086, 'user_stacks': ['Swift', 'Dart', 'SwiftUI', 'ASP.NET', 'Go', 'React', 'NestJS', 'OpenGL', 'jQuery', 'C']},
  {'user_id': 1087, 'user_stacks': ['Java', 'TypeScript', 'Apache Spark', 'SpringBoot', 'Express', 'PHP']},
  {'user_id': 1088, 'user_stacks': ['Blazor', 'Swift']},
  {'user_id': 1089, 'user_stacks': ['Node.js']},
  {'user_id': 1090, 'user_stacks': ['Rust', 'NestJS', 'jQuery', 'Express', 'Laravel', 'Opencv', 'Apache Spark']},
  {'user_id': 1091, 'user_stacks': ['ASP.NET', 'SpringBoot', 'OpenGL', 'NestJS', 'Ruby']},
  {'user_id': 1092, 'user_stacks': ['Electron', 'Rust', 'OpenGL', 'React', 'TensorFlow', 'Lua', 'Torch', 'Laravel', 'AngularJS', 'Pandas']},
  {'user_id': 1093, 'user_stacks': ['Flask', 'C#', 'TensorFlow', 'Dart', 'Ruby on Rails', 'Java', 'Qt', 'Ruby', 'NestJS']},
  {'user_id': 1094, 'user_stacks': ['TypeScript']},
  {'user_id': 1095, 'user_stacks': ['Next.js', 'Torch', 'TypeScript', 'C#', 'TensorFlow', 'jQuery', 'C', 'React']},
  {'user_id': 1096, 'user_stacks': ['Dart', 'C', 'TypeScript', 'AngularJS', 'React Native', 'React', 'Blazor', 'Electron', 'PHP', 'Flask']},
  {'user_id': 1097, 'user_stacks': ['Kotlin', 'ASP.NET', 'Torch', 'Qt']},
  {'user_id': 1098, 'user_stacks': ['Ruby on Rails', 'R', 'Rust', 'Express']},
  {'user_id': 1099, 'user_stacks': ['Go']},
  {'user_id': 1100, 'user_stacks': ['Vue.js', 'Apache Spark', 'Python', 'ASP.NET', 'Java', 'SwiftUI', 'C', 'Angular']},
  {'user_id': 1101, 'user_stacks': ['PyTorch', 'OpenGL']},
  {'user_id': 1102, 'user_stacks': ['Blazor', 'TypeScript', 'PyTorch']},
  {'user_id': 1103, 'user_stacks': ['React', 'TensorFlow', 'Apache Spark', 'HTML/CSS', 'Svelte', 'Django', 'RabbitMQ']},
  {'user_id': 1104, 'user_stacks': ['.NET', 'Ruby on Rails', 'OpenGL', 'Blazor', 'Svelte', 'JavaScript', 'Torch', 'Electron', 'Node.js']},
  {'user_id': 1105, 'user_stacks': ['Java', 'Flask', 'Rust', 'TensorFlow']},
  {'user_id': 1106, 'user_stacks': ['PHP', 'ASP.NET', 'React', 'Dart', 'Opencv', 'Go', 'Next.js', 'React Native', 'Django', 'JavaScript']},
  {'user_id': 1107, 'user_stacks': ['Node.js', 'Java', 'C', 'AngularJS', 'ASP.NET', 'Rust', 'jQuery', 'Express']},
  {'user_id': 1108, 'user_stacks': ['Node.js', 'Swift', 'PyTorch', 'Kotlin', 'JavaScript']},
  {'user_id': 1109, 'user_stacks': ['Pandas', 'C#', 'TypeScript', 'SwiftUI', 'Next.js', 'SpringBoot']},
  {'user_id': 1110, 'user_stacks': ['Java', 'Lua']},
  {'user_id': 1111, 'user_stacks': ['Swift', 'Angular', 'C#', 'JavaScript']},
  {'user_id': 1112, 'user_stacks': ['Next.js', 'Keras']},
  {'user_id': 1113, 'user_stacks': ['R', 'OpenGL', 'Qt', 'Keras', 'React Native', 'Flutter', 'RabbitMQ', 'React', '.NET', 'jQuery']},
  {'user_id': 1114, 'user_stacks': ['Node.js', 'Rust', 'Vue.js', 'Ruby', 'Swift', 'Svelte', 'jQuery', 'Angular', 'C']},
  {'user_id': 1115, 'user_stacks': ['Flutter', 'PHP', 'Go', 'Next.js']},
  {'user_id': 1116, 'user_stacks': ['C', 'Pandas', 'C++', 'OpenGL', 'jQuery', 'Flutter', 'Node.js']},
  {'user_id': 1117, 'user_stacks': ['C#', 'Dart', 'React Native', 'Swift', 'Node.js', 'Ruby on Rails', 'NestJS']},
  {'user_id': 1118, 'user_stacks': ['ASP.NET', 'Ruby on Rails', 'Pandas']},
  {'user_id': 1119, 'user_stacks': ['Swift', 'Next.js', 'C++', 'Opencv', 'R', 'scikit-Learn', 'Express']},
  {'user_id': 1120, 'user_stacks': ['Rust', 'Flutter']},
  {'user_id': 1121, 'user_stacks': ['ASP.NET', 'TypeScript', 'Rust']},
  {'user_id': 1122, 'user_stacks': ['React Native']},
  {'user_id': 1123, 'user_stacks': ['OpenGL', 'Next.js', 'C', 'Flask', 'Django']},
  {'user_id': 1124, 'user_stacks': ['Vue.js', 'Laravel']},
  {'user_id': 1125, 'user_stacks': ['Pandas', 'R', 'Express', 'Flutter']},
  {'user_id': 1126, 'user_stacks': ['ASP.NET']},
  {'user_id': 1127, 'user_stacks': ['Blazor', 'Swift', 'OpenGL']},
  {'user_id': 1128, 'user_stacks': ['Laravel']},
  {'user_id': 1129, 'user_stacks': ['Kotlin', 'TypeScript', 'Apache Spark', 'SpringBoot', '.NET', 'ASP.NET', 'Flask', 'Next.js', 'Express', 'JavaScript']},
  {'user_id': 1130, 'user_stacks': ['PHP', 'Flutter', 'Keras', 'jQuery', 'AngularJS', 'Lua', 'Qt', 'TensorFlow', 'Node.js', 'Ruby']},
  {'user_id': 1131, 'user_stacks': ['Keras', 'Electron', 'scikit-Learn']},
  {'user_id': 1132, 'user_stacks': ['R', 'Blazor', 'Flutter']},
  {'user_id': 1133, 'user_stacks': ['Dart']},
  {'user_id': 1134, 'user_stacks': ['TypeScript', 'Swift', 'Pandas', 'Apache Spark', 'Blazor', 'AngularJS', 'Kotlin', 'ASP.NET', 'JavaScript']},
  {'user_id': 1135, 'user_stacks': ['Opencv', 'Lua', 'scikit-Learn', 'Node.js', 'Go']},
  {'user_id': 1136, 'user_stacks': ['React', 'Java', 'ASP.NET', 'HTML/CSS', 'Express']},
  {'user_id': 1137, 'user_stacks': ['Kotlin', 'Electron', 'OpenGL', 'Pandas', 'PyTorch', 'JavaScript', 'Keras', 'scikit-Learn', 'Dart', 'React']},
  {'user_id': 1138, 'user_stacks': ['C#', 'Keras', 'Laravel', 'C', 'R', 'Flutter', 'OpenGL', 'NestJS']},
  {'user_id': 1139, 'user_stacks': ['Rust', 'Ruby']},
  {'user_id': 1140, 'user_stacks': ['AngularJS', 'Lua', 'Kotlin']},
  {'user_id': 1141, 'user_stacks': ['Go']},
  {'user_id': 1142, 'user_stacks': ['Ruby on Rails']},
  {'user_id': 1143, 'user_stacks': ['Kotlin']},
  {'user_id': 1144, 'user_stacks': ['Node.js', 'Pandas', 'Apache Spark', 'jQuery', 'Go', 'AngularJS', 'React', 'Flutter', 'Vue.js']},
  {'user_id': 1145, 'user_stacks': ['React', 'Torch', 'ASP.NET', 'Node.js']},
  {'user_id': 1146, 'user_stacks': ['Kotlin', 'C++', 'Lua']},
  {'user_id': 1147, 'user_stacks': ['HTML/CSS', 'R', 'AngularJS', 'Ruby', 'React', 'Flutter']},
  {'user_id': 1148, 'user_stacks': ['Blazor', 'AngularJS', 'NestJS', 'R', 'Opencv', 'Node.js']},
  {'user_id': 1149, 'user_stacks': ['Django', 'Vue.js', 'Flutter', 'Express', 'Node.js', 'PyTorch', 'Qt']},
  {'user_id': 1150, 'user_stacks': ['Flutter', 'React Native']},
  {'user_id': 1151, 'user_stacks': ['JavaScript', 'Angular', 'SpringBoot', 'Next.js', 'Laravel']},
  {'user_id': 1152, 'user_stacks': ['Lua', 'Kotlin']},
  {'user_id': 1153, 'user_stacks': ['Ruby on Rails', 'C', 'React Native', 'Express', 'Django', 'TensorFlow', 'Ruby', 'Angular']},
  {'user_id': 1154, 'user_stacks': ['Django', 'PHP', 'Lua', 'React', 'C++', 'TypeScript', 'Qt']},
  {'user_id': 1155, 'user_stacks': ['Rust', 'Vue.js', 'PHP', 'Apache Spark', 'Electron', 'HTML/CSS']},
  {'user_id': 1156, 'user_stacks': ['SpringBoot', 'Svelte', 'TypeScript']},
  {'user_id': 1157, 'user_stacks': ['Flask', 'jQuery', '.NET', 'Electron', 'Angular', 'RabbitMQ', 'Kotlin', 'PHP', 'R', 'PyTorch']},
  {'user_id': 1158, 'user_stacks': ['Vue.js', '.NET', 'Kotlin', 'HTML/CSS', 'Express', 'Keras']},
  {'user_id': 1159, 'user_stacks': ['Kotlin', 'Swift', 'Keras', 'React Native']},
  {'user_id': 1160, 'user_stacks': ['C']},
  {'user_id': 1161, 'user_stacks': ['scikit-Learn', 'NestJS', 'Keras', 'Laravel', 'Swift', 'Qt']},
  {'user_id': 1162, 'user_stacks': ['TensorFlow', 'SpringBoot', 'ASP.NET', 'HTML/CSS', 'Go', 'Flutter', 'Ruby on Rails', 'Laravel', 'R', 'React Native']},
  {'user_id': 1163, 'user_stacks': ['PyTorch', 'React', 'Node.js', 'Flask', 'Go', 'Torch', 'Flutter', 'Angular', 'C']},
  {'user_id': 1164, 'user_stacks': ['Lua', 'C']},
  {'user_id': 1165, 'user_stacks': ['Ruby', '.NET']},
  {'user_id': 1166, 'user_stacks': ['TensorFlow', 'Torch', 'Lua', 'React Native', 'R', 'React', 'OpenGL']},
  {'user_id': 1167, 'user_stacks': ['HTML/CSS', 'Next.js', 'ASP.NET', 'Keras', 'C#', 'SwiftUI']},
  {'user_id': 1168, 'user_stacks': ['AngularJS', 'Flutter', 'Angular', 'Vue.js', 'C++', 'scikit-Learn', 'SwiftUI', 'Python', 'Go']},
  {'user_id': 1169, 'user_stacks': ['Express', 'Ruby', 'Lua', 'NestJS', 'Next.js']},
  {'user_id': 1170, 'user_stacks': ['Ruby', 'HTML/CSS', 'JavaScript']},
  {'user_id': 1171, 'user_stacks': ['TypeScript', 'C', 'Swift', 'NestJS']},
  {'user_id': 1172, 'user_stacks': ['Python', 'Blazor']},
  {'user_id': 1173, 'user_stacks': ['Node.js', 'Svelte', 'Vue.js', 'SwiftUI', 'R', 'SpringBoot', 'TensorFlow', 'Pandas']},
  {'user_id': 1174, 'user_stacks': ['SwiftUI', '.NET', 'Express', 'Vue.js', 'Apache Spark', 'Lua', 'ASP.NET', 'Rust', 'R', 'SpringBoot']},
  {'user_id': 1175, 'user_stacks': ['Flutter', 'Laravel', 'OpenGL', 'Apache Spark', 'Ruby on Rails']},
  {'user_id': 1176, 'user_stacks': ['.NET', 'React Native', 'HTML/CSS', 'Blazor', 'C#', 'Python', 'AngularJS']},
  {'user_id': 1177, 'user_stacks': ['Pandas']},
  {'user_id': 1178, 'user_stacks': ['SpringBoot', 'Torch']},
  {'user_id': 1179, 'user_stacks': ['Opencv', 'Keras', 'React Native', 'Qt', 'Next.js', '.NET', 'AngularJS', 'Ruby on Rails', 'Ruby']},
  {'user_id': 1180, 'user_stacks': ['Ruby on Rails', 'Flutter', 'Rust', 'NestJS', 'TensorFlow', 'React Native', 'TypeScript', 'Apache Spark', 'React', '.NET']},
  {'user_id': 1181, 'user_stacks': ['Ruby on Rails', 'C', 'C++', 'ASP.NET', 'Keras', 'SpringBoot', 'OpenGL']},
  {'user_id': 1182, 'user_stacks': ['R', 'Laravel']},
  {'user_id': 1183, 'user_stacks': ['React Native', 'Electron', 'Next.js']},
  {'user_id': 1184, 'user_stacks': ['Blazor', 'jQuery', 'Vue.js', 'Laravel', 'TypeScript', 'C++', 'Electron', 'C#', 'PHP']},
  {'user_id': 1185, 'user_stacks': ['SwiftUI', 'RabbitMQ', 'Node.js', 'Kotlin', 'JavaScript', 'Java', 'Electron', 'Keras', 'HTML/CSS', 'Dart']},
  {'user_id': 1186, 'user_stacks': ['TensorFlow', 'PyTorch', 'TypeScript', 'Lua', 'Angular', 'RabbitMQ', 'Node.js', 'NestJS', 'jQuery', 'SpringBoot']},
  {'user_id': 1187, 'user_stacks': ['HTML/CSS', 'Ruby', 'Lua', 'Electron', 'Pandas', 'C++', 'Apache Spark', 'React']},
  {'user_id': 1188, 'user_stacks': ['NestJS', 'R', 'Python', 'PHP', '.NET', 'Apache Spark', 'Electron', 'Angular', 'Kotlin', 'OpenGL']},
  {'user_id': 1189, 'user_stacks': ['C#', 'OpenGL', 'Flutter', 'Dart', 'NestJS', 'TypeScript', 'React']},
  {'user_id': 1190, 'user_stacks': ['AngularJS', 'C#', 'Rust']},
  {'user_id': 1191, 'user_stacks': ['AngularJS', 'Vue.js']},
  {'user_id': 1192, 'user_stacks': ['Django', 'ASP.NET', 'TypeScript', 'Python', 'Express', 'PHP']},
  {'user_id': 1193, 'user_stacks': ['React Native', 'Keras', 'scikit-Learn', 'Pandas', 'Go', 'PHP', 'Ruby on Rails']},
  {'user_id': 1194, 'user_stacks': ['Vue.js', 'NestJS', 'TypeScript']},
  {'user_id': 1195, 'user_stacks': ['Kotlin', 'Go', 'Flask']},
  {'user_id': 1196, 'user_stacks': ['OpenGL', 'NestJS', 'RabbitMQ']},
  {'user_id': 1197, 'user_stacks': ['Kotlin', 'React', 'jQuery', 'PHP', 'OpenGL', '.NET', 'React Native', 'Rust', 'scikit-Learn']},
  {'user_id': 1198, 'user_stacks': ['React Native', 'C#', 'PyTorch', '.NET', 'AngularJS', 'scikit-Learn', 'Lua', 'HTML/CSS', 'Rust']},
  {'user_id': 1199, 'user_stacks': ['Vue.js', 'Kotlin', 'Laravel']},
  {'user_id': 1200, 'user_stacks': ['R', 'NestJS']},
  {'user_id': 1201, 'user_stacks': ['React Native', 'C++', 'PHP', 'R', 'HTML/CSS', 'Django', 'Pandas', 'Torch']},
  {'user_id': 1202, 'user_stacks': ['Node.js', 'Qt', 'SwiftUI', 'jQuery', 'scikit-Learn', 'TensorFlow', 'SpringBoot', 'Next.js', 'Swift', 'R']},
  {'user_id': 1203, 'user_stacks': ['React Native', 'Django', 'Express', 'Go', 'PyTorch', 'Apache Spark', 'AngularJS', 'PHP', '.NET']},
  {'user_id': 1204, 'user_stacks': ['C#', 'Flutter', 'Lua', 'Electron', 'SpringBoot', 'Ruby', 'ASP.NET', 'PyTorch']},
  {'user_id': 1205, 'user_stacks': ['Apache Spark', 'Go', 'Next.js', 'JavaScript', 'Svelte', 'Flask', 'Ruby on Rails']},
  {'user_id': 1206, 'user_stacks': ['Apache Spark', 'Dart', 'Django', 'Go', 'Flask', 'C#']},
  {'user_id': 1207, 'user_stacks': ['Java', 'Svelte', 'Blazor', 'Laravel', 'Ruby on Rails', 'Apache Spark', 'TensorFlow', 'PHP', 'C++']},
  {'user_id': 1208, 'user_stacks': ['OpenGL', 'Node.js', 'R', 'Flask', 'Rust', 'RabbitMQ', 'Qt', 'Dart']},
  {'user_id': 1209, 'user_stacks': ['Kotlin', 'TensorFlow', 'Angular', 'React Native', 'Laravel']},
  {'user_id': 1210, 'user_stacks': ['Ruby', 'Pandas', 'Lua', 'Angular', 'Python', 'TensorFlow', 'RabbitMQ', 'PyTorch', 'Dart', 'Flutter']},
  {'user_id': 1211, 'user_stacks': ['R']},
  {'user_id': 1212, 'user_stacks': ['TypeScript', 'NestJS']},
  {'user_id': 1213, 'user_stacks': ['Qt', 'Ruby on Rails', 'Vue.js', 'Ruby', 'C++', 'React', 'Dart']},
  {'user_id': 1214, 'user_stacks': ['Java', 'Lua', 'React']},
  {'user_id': 1215, 'user_stacks': ['R']},
  {'user_id': 1216, 'user_stacks': ['Django', 'Lua', 'Torch', 'Vue.js']},
  {'user_id': 1217, 'user_stacks': ['Qt', 'scikit-Learn', 'Opencv', 'Keras', 'AngularJS', 'Next.js', 'Flutter', 'Ruby', 'HTML/CSS']},
  {'user_id': 1218, 'user_stacks': ['Qt', 'Electron', 'Django', 'C#']},
  {'user_id': 1219, 'user_stacks': ['Electron', 'Flask', 'Swift']},
  {'user_id': 1220, 'user_stacks': ['scikit-Learn', 'Ruby', 'Python']},
  {'user_id': 1221, 'user_stacks': ['Express']},
  {'user_id': 1222, 'user_stacks': ['Keras', 'Flutter', 'Lua', 'Go', 'Java', 'R', 'Pandas', 'Angular', 'OpenGL']},
  {'user_id': 1223, 'user_stacks': ['TypeScript', 'React', 'Angular', 'Dart', 'Flask']},
  {'user_id': 1224, 'user_stacks': ['AngularJS', 'Laravel', 'Swift', 'Torch', 'PyTorch', 'scikit-Learn', 'Express', 'Ruby on Rails']},
  {'user_id': 1225, 'user_stacks': ['PHP', 'React Native']},
  {'user_id': 1226, 'user_stacks': ['React', 'Ruby', 'Flutter', 'Blazor', 'Qt', 'ASP.NET', 'JavaScript', 'TypeScript', 'Torch']},
  {'user_id': 1227, 'user_stacks': ['HTML/CSS', 'R', 'Opencv']},
  {'user_id': 1228, 'user_stacks': ['Blazor', 'Python', 'Lua', 'Keras', 'Vue.js', 'NestJS', 'scikit-Learn', 'Next.js']},
  {'user_id': 1229, 'user_stacks': ['Flask', 'Go', 'Ruby', 'ASP.NET', 'HTML/CSS', 'Java']},
  {'user_id': 1230, 'user_stacks': ['Apache Spark', 'Electron']},
  {'user_id': 1231, 'user_stacks': ['R', 'C++']},
  {'user_id': 1232, 'user_stacks': ['Kotlin', 'React Native', 'C++', 'ASP.NET', 'Pandas', 'scikit-Learn', 'Node.js']},
  {'user_id': 1233, 'user_stacks': ['R', 'Rust', 'PHP', 'Go', 'Vue.js', 'AngularJS', 'Kotlin', 'Apache Spark']},
  {'user_id': 1234, 'user_stacks': ['scikit-Learn']},
  {'user_id': 1235, 'user_stacks': ['Flutter', 'Next.js', 'TensorFlow', 'R', 'C#']},
  {'user_id': 1236, 'user_stacks': ['C', 'Flutter']},
  {'user_id': 1237, 'user_stacks': ['TensorFlow', '.NET']},
  {'user_id': 1238, 'user_stacks': ['C#', 'R', 'Apache Spark', 'NestJS']},
  {'user_id': 1239, 'user_stacks': ['Python', 'PyTorch', 'Angular', 'Express', 'Laravel', 'Dart', 'TensorFlow', 'Swift']},
  {'user_id': 1240, 'user_stacks': ['React', 'JavaScript', 'Dart', 'C#', 'Go', 'jQuery', 'Torch']},
  {'user_id': 1241, 'user_stacks': ['TensorFlow', 'Keras', 'Node.js', 'C', 'Django', 'Ruby on Rails', 'SwiftUI', 'R', 'React Native']},
  {'user_id': 1242, 'user_stacks': ['React Native', 'scikit-Learn']},
  {'user_id': 1243, 'user_stacks': ['Svelte', 'TypeScript', 'Keras', 'SpringBoot', 'RabbitMQ', 'Django', 'Vue.js']},
  {'user_id': 1244, 'user_stacks': ['Apache Spark', 'Kotlin', 'Python', 'PHP', 'Ruby on Rails']},
  {'user_id': 1245, 'user_stacks': ['RabbitMQ', 'C', 'Lua', 'Electron']},
  {'user_id': 1246, 'user_stacks': ['Swift', 'Ruby on Rails', 'Opencv', 'TypeScript', 'HTML/CSS', 'Torch']},
  {'user_id': 1247, 'user_stacks': ['Dart', 'React', 'Python', 'C']},
  {'user_id': 1248, 'user_stacks': ['Ruby on Rails', 'NestJS', 'Blazor', 'PHP']},
  {'user_id': 1249, 'user_stacks': ['React', 'ASP.NET', 'TypeScript', 'Qt', 'Express', 'SwiftUI', 'C#', 'Flutter', 'Apache Spark', 'scikit-Learn']},
  {'user_id': 1250, 'user_stacks': ['NestJS', 'Ruby']},
  {'user_id': 1251, 'user_stacks': ['Kotlin', 'Keras', 'TypeScript']},
  {'user_id': 1252, 'user_stacks': ['Keras', 'Ruby on Rails']},
  {'user_id': 1253, 'user_stacks': ['Lua', 'SpringBoot', 'Ruby on Rails', 'JavaScript']},
  {'user_id': 1254, 'user_stacks': ['Keras', 'React Native', 'OpenGL', 'jQuery', 'Vue.js', 'Dart', 'Electron', 'C++']},
  {'user_id': 1255, 'user_stacks': ['PyTorch', 'Node.js', 'Flask', 'Rust', 'React Native', 'Electron']},
  {'user_id': 1256, 'user_stacks': ['Flutter']},
  {'user_id': 1257, 'user_stacks': ['React', 'Flask', 'PyTorch', 'HTML/CSS', 'Pandas', 'Vue.js']},
  {'user_id': 1258, 'user_stacks': ['JavaScript', 'Next.js', 'Ruby on Rails', 'SwiftUI', 'C']},
  {'user_id': 1259, 'user_stacks': ['Go', 'ASP.NET']},
  {'user_id': 1260, 'user_stacks': ['Blazor', 'AngularJS', 'NestJS']},
  {'user_id': 1261, 'user_stacks': ['Python', 'Qt', 'Django', 'Express', '.NET']},
  {'user_id': 1262, 'user_stacks': ['Rust', 'C', 'TensorFlow', '.NET', 'AngularJS', 'SpringBoot', 'React', 'Lua']},
  {'user_id': 1263, 'user_stacks': ['Laravel', 'Flask', 'React Native', 'Kotlin']},
  {'user_id': 1264, 'user_stacks': ['Swift', 'Qt', 'Opencv', 'Python', 'Lua', 'Torch', 'Django']},
  {'user_id': 1265, 'user_stacks': ['scikit-Learn', 'Apache Spark']},
  {'user_id': 1266, 'user_stacks': ['.NET', 'scikit-Learn', 'Laravel', 'Torch', 'Angular', 'HTML/CSS', 'RabbitMQ', 'Swift', 'Vue.js']},
  {'user_id': 1267, 'user_stacks': ['Opencv', 'Go', 'Vue.js', 'Blazor', 'NestJS', 'SpringBoot', 'React Native', '.NET']},
  {'user_id': 1268, 'user_stacks': ['RabbitMQ', 'scikit-Learn', 'Opencv', 'Pandas', 'Flask', 'PyTorch', 'Torch', 'jQuery', 'Electron', 'OpenGL']},
  {'user_id': 1269, 'user_stacks': ['Node.js', 'jQuery', 'Opencv', 'PyTorch', 'ASP.NET', 'Keras', 'R']},
  {'user_id': 1270, 'user_stacks': ['Flutter', 'Lua']},
  {'user_id': 1271, 'user_stacks': ['ASP.NET', 'Dart', 'Ruby', 'PHP', 'Python', 'Vue.js', 'TypeScript', 'Flutter', 'Java', 'React Native']},
  {'user_id': 1272, 'user_stacks': ['Ruby on Rails', 'AngularJS', 'JavaScript', 'Blazor', 'Django', 'Flask', 'TypeScript']},
  {'user_id': 1273, 'user_stacks': ['Express', 'Torch', 'RabbitMQ', 'Angular', 'Dart', 'Apache Spark', 'OpenGL']},
  {'user_id': 1274, 'user_stacks': ['Qt']},
  {'user_id': 1275, 'user_stacks': ['jQuery', 'Python']},
  {'user_id': 1276, 'user_stacks': ['C#', 'C++', 'jQuery', 'PHP', 'scikit-Learn', 'Opencv', 'Flask', 'Next.js']},
  {'user_id': 1277, 'user_stacks': ['Django', 'Java', 'Svelte', 'Pandas', 'Node.js']},
  {'user_id': 1278, 'user_stacks': ['Rust', 'Vue.js', 'AngularJS', 'PHP', 'C++', 'C#', '.NET']},
  {'user_id': 1279, 'user_stacks': ['Dart', 'C', 'scikit-Learn', 'PyTorch', 'Flutter', 'Ruby', 'Node.js', 'Pandas']},
  {'user_id': 1280, 'user_stacks': ['RabbitMQ', 'TensorFlow', 'TypeScript', 'C++', 'JavaScript', 'jQuery', 'Django']},
  {'user_id': 1281, 'user_stacks': ['Ruby on Rails', 'SwiftUI', 'Kotlin', 'Blazor', 'Ruby', 'Flask', 'OpenGL', 'Pandas', 'React Native']},
  {'user_id': 1282, 'user_stacks': ['PHP', 'jQuery', 'C', 'Apache Spark']},
  {'user_id': 1283, 'user_stacks': ['Blazor', 'Ruby on Rails', 'Svelte', 'AngularJS', 'Java', 'Qt', 'Torch', 'Kotlin', 'Laravel', 'Apache Spark']},
  {'user_id': 1284, 'user_stacks': ['Pandas', 'C', 'React Native', 'C#', 'Flutter', 'R']},
  {'user_id': 1285, 'user_stacks': ['Python', 'Express', 'C++', 'Qt', 'Torch', 'Rust', 'React Native', 'Apache Spark']},
  {'user_id': 1286, 'user_stacks': ['Swift', 'HTML/CSS', 'Java', 'Electron', 'C', 'Ruby on Rails', 'Flutter']},
  {'user_id': 1287, 'user_stacks': ['Apache Spark', 'Svelte', 'Angular', 'Dart', 'Torch', 'Lua', 'PyTorch', 'C', 'NestJS']},
  {'user_id': 1288, 'user_stacks': ['Kotlin', 'Laravel', 'Apache Spark', 'Angular']},
  {'user_id': 1289, 'user_stacks': ['Angular', 'Vue.js', 'PyTorch']},
  {'user_id': 1290, 'user_stacks': ['Flutter', 'Angular', 'React']},
  {'user_id': 1291, 'user_stacks': ['Flutter', 'React', 'Rust', 'Java', 'Angular', 'Next.js', 'Node.js']},
  {'user_id': 1292, 'user_stacks': ['Ruby', 'Svelte', 'NestJS', 'Java', 'Torch', 'Flask']},
  {'user_id': 1293, 'user_stacks': ['Next.js', 'Django', 'React Native', 'Flutter', 'Pandas', 'Electron', 'PyTorch']},
  {'user_id': 1294, 'user_stacks': ['TypeScript', 'Flutter', 'Svelte', 'Angular', 'Torch', 'Express', 'Ruby', 'C#', 'C', 'scikit-Learn']},
  {'user_id': 1295, 'user_stacks': ['JavaScript', 'Next.js', '.NET', 'OpenGL', 'Flutter', 'TypeScript', 'Ruby on Rails', 'Swift', 'Vue.js', 'Dart']},
  {'user_id': 1296, 'user_stacks': ['RabbitMQ', 'ASP.NET', 'C', 'Swift', 'C++', 'Lua', 'Apache Spark', 'Flask', 'Express']},
  {'user_id': 1297, 'user_stacks': ['SpringBoot', 'Kotlin', 'TypeScript', 'Flask', 'C#']},
  {'user_id': 1298, 'user_stacks': ['RabbitMQ', 'AngularJS', 'TensorFlow', 'JavaScript']},
  {'user_id': 1299, 'user_stacks': ['Pandas', 'HTML/CSS']},
  {'user_id': 1300, 'user_stacks': ['Rust', 'Python', 'Blazor', 'Pandas', 'Apache Spark', 'Keras', 'PyTorch', 'Django', 'C']},
  {'user_id': 1301, 'user_stacks': ['Flutter', 'ASP.NET', 'Kotlin', 'Angular', 'Lua', 'Vue.js', 'React Native', 'HTML/CSS']},
  {'user_id': 1302, 'user_stacks': ['Qt', 'Flutter']},
  {'user_id': 1303, 'user_stacks': ['Node.js', 'Django', 'Laravel', 'Qt', 'Svelte', 'Go', 'TypeScript', 'TensorFlow', 'ASP.NET', 'AngularJS']},
  {'user_id': 1304, 'user_stacks': ['OpenGL', 'Kotlin', 'Dart', 'AngularJS']},
  {'user_id': 1305, 'user_stacks': ['scikit-Learn', 'TensorFlow', 'Kotlin', 'Swift', 'TypeScript', 'Node.js', 'JavaScript', 'Flask', 'AngularJS']},
  {'user_id': 1306, 'user_stacks': ['Django', 'Next.js', 'C', 'Angular', 'Express', 'ASP.NET', 'SpringBoot']},
  {'user_id': 1307, 'user_stacks': ['Pandas', 'Blazor', 'PyTorch', 'jQuery']},
  {'user_id': 1308, 'user_stacks': ['Rust', 'Electron', 'C#', 'JavaScript', 'Torch', 'TensorFlow', 'Vue.js', 'Java', 'Opencv', 'Swift']},
  {'user_id': 1309, 'user_stacks': ['Svelte']},
  {'user_id': 1310, 'user_stacks': ['Go', 'Vue.js', 'Laravel', 'TypeScript', 'Dart']},
  {'user_id': 1311, 'user_stacks': ['Express', 'Ruby', 'NestJS']},
  {'user_id': 1312, 'user_stacks': ['React']},
  {'user_id': 1313, 'user_stacks': ['PHP', 'Django', 'jQuery', 'Angular', '.NET', 'TensorFlow', 'Keras', 'Flutter']},
  {'user_id': 1314, 'user_stacks': ['Node.js', 'Angular', 'Python', 'Electron']},
  {'user_id': 1315, 'user_stacks': ['Torch', 'Flask', 'Apache Spark']},
  {'user_id': 1316, 'user_stacks': ['jQuery', 'AngularJS', 'Laravel', 'Torch', 'Flutter', 'Express', 'C#']},
  {'user_id': 1317, 'user_stacks': ['Java']},
  {'user_id': 1318, 'user_stacks': ['C++', 'AngularJS', 'SpringBoot', 'Rust']},
  {'user_id': 1319, 'user_stacks': ['Rust', 'Apache Spark', 'Pandas', 'HTML/CSS', 'AngularJS', 'Next.js', 'Go', 'TypeScript', 'Python']},
  {'user_id': 1320, 'user_stacks': ['Pandas', 'SpringBoot', 'jQuery', '.NET', 'RabbitMQ']},
  {'user_id': 1321, 'user_stacks': ['Java', 'Rust', 'Laravel']},
  {'user_id': 1322, 'user_stacks': ['Swift', 'Rust', 'Apache Spark', 'ASP.NET', 'React', 'Qt']},
  {'user_id': 1323, 'user_stacks': ['TypeScript', 'React Native', 'Python', 'Next.js', 'Flutter', 'AngularJS', 'Go']},
  {'user_id': 1324, 'user_stacks': ['OpenGL', 'TypeScript', 'Laravel']},
  {'user_id': 1325, 'user_stacks': ['Go']},
  {'user_id': 1326, 'user_stacks': ['Keras', 'Laravel', 'JavaScript', 'HTML/CSS', 'Angular', 'C', 'React Native', 'PHP', 'AngularJS', 'Express']},
  {'user_id': 1327, 'user_stacks': ['Electron', 'Keras', 'Dart', 'Flask', 'Angular', 'PHP', 'Flutter', 'React Native', 'Blazor', 'TensorFlow']},
  {'user_id': 1328, 'user_stacks': ['React', 'SwiftUI', 'C', 'Electron', 'jQuery', 'Java']},
  {'user_id': 1329, 'user_stacks': ['Python']},
  {'user_id': 1330, 'user_stacks': ['Python', 'Go', 'Flutter', 'Torch', 'OpenGL', 'Next.js', 'Django']},
  {'user_id': 1331, 'user_stacks': ['R', 'Electron', 'Kotlin', 'Torch', 'Flutter', 'C++', 'React Native', 'Qt']},
  {'user_id': 1332, 'user_stacks': ['Flask', 'JavaScript', '.NET']},
  {'user_id': 1333, 'user_stacks': ['scikit-Learn', 'Flask', 'AngularJS', 'Node.js', 'React Native', 'React']},
  {'user_id': 1334, 'user_stacks': ['TypeScript', '.NET', 'SpringBoot', 'PHP', 'Laravel']},
  {'user_id': 1335, 'user_stacks': ['HTML/CSS', 'Opencv', 'Ruby on Rails', 'Rust', 'Dart', 'Python', 'React']},
  {'user_id': 1336, 'user_stacks': ['Blazor', 'Swift', 'Laravel', 'NestJS', 'Dart', 'TensorFlow', 'PHP', 'JavaScript', 'Kotlin']},
  {'user_id': 1337, 'user_stacks': ['Express', 'Electron', 'C', 'Django', 'SwiftUI', 'OpenGL', 'NestJS', 'scikit-Learn']},
  {'user_id': 1338, 'user_stacks': ['HTML/CSS', 'Flutter', 'Svelte', 'Torch', 'Python', 'Blazor', 'SpringBoot', 'Express', 'AngularJS']},
  {'user_id': 1339, 'user_stacks': ['Ruby on Rails', 'SwiftUI', 'Dart', 'Go', 'Qt', 'Keras', 'Flask']},
  {'user_id': 1340, 'user_stacks': ['.NET', 'Electron', 'Angular', 'Rust', 'R']},
  {'user_id': 1341, 'user_stacks': ['Torch', 'C#', 'Kotlin', 'Vue.js', 'R', 'Flask', 'Go', 'Svelte', 'NestJS', 'OpenGL']},
  {'user_id': 1342, 'user_stacks': ['Angular', 'PHP', 'scikit-Learn', 'SpringBoot', 'React', 'C#']},
  {'user_id': 1343, 'user_stacks': ['Electron', 'Kotlin', 'Laravel', 'Flutter', 'Torch']},
  {'user_id': 1344, 'user_stacks': ['Python', 'Keras', 'Django', 'PyTorch', 'Flask', 'scikit-Learn', 'Electron', 'Apache Spark', 'Opencv']},
  {'user_id': 1345, 'user_stacks': ['.NET', 'Svelte', 'Vue.js', 'JavaScript', 'C++', 'NestJS', 'Java', 'Node.js', 'Torch', 'TensorFlow']},
  {'user_id': 1346, 'user_stacks': ['Flask', 'Swift', 'SwiftUI']},
  {'user_id': 1347, 'user_stacks': ['Swift', 'ASP.NET', 'Python']},
  {'user_id': 1348, 'user_stacks': ['ASP.NET', 'TensorFlow', 'Flask', 'Vue.js', 'Svelte', 'Ruby on Rails']},
  {'user_id': 1349, 'user_stacks': ['Svelte', 'Swift', 'jQuery']},
  {'user_id': 1350, 'user_stacks': ['Swift', 'Keras', 'Svelte', 'Vue.js', 'HTML/CSS']},
  {'user_id': 1351, 'user_stacks': ['jQuery']},
  {'user_id': 1352, 'user_stacks': ['Kotlin', 'Torch', 'React', 'JavaScript', 'jQuery', 'Go', 'HTML/CSS']},
  {'user_id': 1353, 'user_stacks': ['Next.js', 'Ruby', 'TypeScript', 'ASP.NET', 'Ruby on Rails', 'Apache Spark', 'Torch', 'HTML/CSS', 'Angular']},
  {'user_id': 1354, 'user_stacks': ['Opencv', 'Apache Spark', 'JavaScript', 'Qt', 'AngularJS']},
  {'user_id': 1355, 'user_stacks': ['Opencv', 'Ruby', 'Vue.js']},
  {'user_id': 1356, 'user_stacks': ['TensorFlow', 'Python', 'Apache Spark', 'Angular', 'Keras']},
  {'user_id': 1357, 'user_stacks': ['Node.js', 'C', 'Flask', 'Qt', 'React Native', 'ASP.NET', 'Vue.js', 'Go']},
  {'user_id': 1358, 'user_stacks': ['Apache Spark', 'PyTorch']},
  {'user_id': 1359, 'user_stacks': ['PyTorch', 'Dart', 'AngularJS', 'Torch', 'Qt', 'Swift']},
  {'user_id': 1360, 'user_stacks': ['React', 'Pandas', 'Electron', 'TensorFlow', 'Qt', 'Blazor', 'JavaScript', 'Ruby on Rails']},
  {'user_id': 1361, 'user_stacks': ['Torch', 'Keras', 'Go', 'JavaScript', 'Rust', 'SwiftUI', 'TensorFlow']},
  {'user_id': 1362, 'user_stacks': ['Ruby on Rails', 'PHP', 'Svelte']},
  {'user_id': 1363, 'user_stacks': ['scikit-Learn', 'Qt', 'React', 'PHP', 'C', 'Python']},
  {'user_id': 1364, 'user_stacks': ['RabbitMQ', 'Dart', 'Express', 'Apache Spark', 'scikit-Learn', 'AngularJS', 'Opencv', 'Keras']},
  {'user_id': 1365, 'user_stacks': ['Dart', 'Laravel', 'Flutter']},
  {'user_id': 1366, 'user_stacks': ['Go', 'SwiftUI', '.NET', 'Torch', 'Python', 'Rust', 'scikit-Learn', 'Keras', 'HTML/CSS', 'Next.js']},
  {'user_id': 1367, 'user_stacks': ['TypeScript', 'React Native', 'PyTorch', 'Django', 'Qt', 'React', 'Keras']},
  {'user_id': 1368, 'user_stacks': ['Swift', 'SwiftUI', 'TypeScript']},
  {'user_id': 1369, 'user_stacks': ['NestJS', 'scikit-Learn', 'Go', 'AngularJS', 'Django', 'TensorFlow', 'Laravel', 'SwiftUI', 'Angular']},
  {'user_id': 1370, 'user_stacks': ['Python', 'Qt', 'Torch', 'Ruby']},
  {'user_id': 1371, 'user_stacks': ['Ruby on Rails', 'C#', 'Qt', 'PHP', 'Flask', 'C', 'TypeScript']},
  {'user_id': 1372, 'user_stacks': ['TypeScript', 'Vue.js', 'PHP']},
  {'user_id': 1373, 'user_stacks': ['ASP.NET', 'React', 'Node.js', 'Rust', 'jQuery', 'PyTorch', 'Flask', 'Kotlin', 'Dart', 'SpringBoot']},
  {'user_id': 1374, 'user_stacks': ['Vue.js']},
  {'user_id': 1375, 'user_stacks': ['Python', 'Electron', 'Node.js', 'OpenGL', 'PyTorch', 'SpringBoot', 'Laravel', 'jQuery', '.NET', 'Blazor']},
  {'user_id': 1376, 'user_stacks': ['React', 'Kotlin']},
  {'user_id': 1377, 'user_stacks': ['TypeScript', 'Ruby', 'Go', 'Express', 'Node.js', 'C#', 'Kotlin', 'Apache Spark']},
  {'user_id': 1378, 'user_stacks': ['JavaScript', 'TensorFlow', 'OpenGL', 'Pandas', 'Dart', 'Go']},
  {'user_id': 1379, 'user_stacks': ['C++', '.NET', 'PyTorch', 'Electron', 'Dart', 'PHP', 'OpenGL', 'Rust', 'Python', 'Node.js']},
  {'user_id': 1380, 'user_stacks': ['Swift', 'jQuery']},
  {'user_id': 1381, 'user_stacks': ['Next.js']},
  {'user_id': 1382, 'user_stacks': ['.NET', 'HTML/CSS', 'Ruby on Rails', 'Lua']},
  {'user_id': 1383, 'user_stacks': ['Lua', 'Opencv', 'C', 'Torch']},
  {'user_id': 1384, 'user_stacks': ['PyTorch', 'Opencv', 'Lua']},
  {'user_id': 1385, 'user_stacks': ['Svelte', 'Kotlin', 'Torch', 'TypeScript']},
  {'user_id': 1386, 'user_stacks': ['Express', 'Keras', 'NestJS', 'Flask']},
  {'user_id': 1387, 'user_stacks': ['C#', 'Express']},
  {'user_id': 1388, 'user_stacks': ['C++', 'Flask', 'Next.js', 'Blazor', 'Node.js', 'NestJS', 'Torch', 'AngularJS']},
  {'user_id': 1389, 'user_stacks': ['TypeScript', 'Express', 'C++', 'AngularJS', 'Lua']},
  {'user_id': 1390, 'user_stacks': ['Ruby on Rails', 'Java', 'React Native', 'TensorFlow']},
  {'user_id': 1391, 'user_stacks': ['Qt', 'jQuery', 'Rust', 'Dart', 'OpenGL', 'PyTorch', 'SwiftUI', 'Laravel', 'SpringBoot']},
  {'user_id': 1392, 'user_stacks': ['Vue.js', 'RabbitMQ', 'Keras', 'Svelte', 'Flutter']},
  {'user_id': 1393, 'user_stacks': ['Electron', 'React', 'Keras', 'PyTorch']},
  {'user_id': 1394, 'user_stacks': ['Electron', 'jQuery', 'React', 'Vue.js', 'Opencv', 'Rust', 'Torch', 'SpringBoot', 'NestJS', 'C']},
  {'user_id': 1395, 'user_stacks': ['OpenGL', 'Qt', 'Django', 'Express']},
  {'user_id': 1396, 'user_stacks': ['Lua', 'Django', 'SwiftUI', 'HTML/CSS']},
  {'user_id': 1397, 'user_stacks': ['Java', 'Python', 'ASP.NET', 'Keras', 'scikit-Learn']},
  {'user_id': 1398, 'user_stacks': ['TensorFlow', 'Laravel', 'Pandas', 'Go', 'C#']},
  {'user_id': 1399, 'user_stacks': ['.NET', 'Ruby on Rails', 'R', 'TensorFlow', 'Flutter', 'React Native', 'PHP', 'ASP.NET']},
  {'user_id': 1400, 'user_stacks': ['Qt', 'JavaScript', 'Opencv', 'R', 'PHP', 'Python']},
  {'user_id': 1401, 'user_stacks': ['C']},
  {'user_id': 1402, 'user_stacks': ['Opencv', 'OpenGL']},
  {'user_id': 1403, 'user_stacks': ['Blazor']},
  {'user_id': 1404, 'user_stacks': ['OpenGL', 'R', 'Rust', 'RabbitMQ', 'Django', 'React Native', 'Express', 'Next.js', 'C++', 'Kotlin']},
  {'user_id': 1405, 'user_stacks': ['Swift', 'React', 'Go']},
  {'user_id': 1406, 'user_stacks': ['Blazor', 'OpenGL', 'Kotlin', 'Flutter', 'Java', 'Swift', 'PyTorch', 'ASP.NET', 'TensorFlow']},
  {'user_id': 1407, 'user_stacks': ['Vue.js', 'Keras', 'Express', 'scikit-Learn', 'ASP.NET', 'R']},
  {'user_id': 1408, 'user_stacks': ['Java', 'Svelte', 'Node.js', 'Go', 'Torch', 'Flutter']},
  {'user_id': 1409, 'user_stacks': ['Opencv']},
  {'user_id': 1410, 'user_stacks': ['Dart', 'Go', 'C', 'Pandas', 'Keras', 'Rust', 'Ruby on Rails']},
  {'user_id': 1411, 'user_stacks': ['Dart', 'Qt', 'Electron', 'NestJS', 'C++', 'Lua', 'RabbitMQ', 'R', 'Ruby']},
  {'user_id': 1412, 'user_stacks': ['Lua', 'Keras', 'Ruby']},
  {'user_id': 1413, 'user_stacks': ['Pandas', 'C#', 'AngularJS', 'Opencv', 'TypeScript', 'Rust', 'C', 'SpringBoot']},
  {'user_id': 1414, 'user_stacks': ['NestJS', 'Node.js', 'Lua', 'Apache Spark', 'Swift', 'SwiftUI', 'TypeScript']},
  {'user_id': 1415, 'user_stacks': ['TensorFlow', 'Go', 'Keras', 'Torch']},
  {'user_id': 1416, 'user_stacks': ['Keras']},
  {'user_id': 1417, 'user_stacks': ['.NET', 'scikit-Learn', 'Torch', 'Vue.js', 'Lua', 'SwiftUI', 'Electron', 'React', 'AngularJS']},
  {'user_id': 1418, 'user_stacks': ['PHP', 'Electron', 'Flutter', 'SwiftUI', 'C#', 'NestJS', 'TensorFlow', '.NET', 'HTML/CSS', 'scikit-Learn']},
  {'user_id': 1419, 'user_stacks': ['Blazor', 'PHP', 'Java', 'Qt']},
  {'user_id': 1420, 'user_stacks': ['Keras', 'SwiftUI']},
  {'user_id': 1421, 'user_stacks': ['React Native', 'RabbitMQ']},
  {'user_id': 1422, 'user_stacks': ['Lua', 'Qt', 'Torch', 'Rust', 'Flask', 'Pandas']},
  {'user_id': 1423, 'user_stacks': ['C']},
  {'user_id': 1424, 'user_stacks': ['Node.js', 'ASP.NET', 'Python', 'OpenGL', 'Dart', 'C++', 'RabbitMQ', 'Ruby on Rails', 'Svelte']},
  {'user_id': 1425, 'user_stacks': ['.NET', 'R', 'AngularJS', 'Next.js', 'React Native', 'Ruby', 'scikit-Learn', 'Django', 'Java']},
  {'user_id': 1426, 'user_stacks': ['Rust']},
  {'user_id': 1427, 'user_stacks': ['React']},
  {'user_id': 1428, 'user_stacks': ['OpenGL', 'Node.js', 'scikit-Learn', 'RabbitMQ', 'AngularJS', 'Flutter', 'Pandas', 'JavaScript', 'TensorFlow', 'SpringBoot']},
  {'user_id': 1429, 'user_stacks': ['PHP', 'scikit-Learn', 'Kotlin', 'Ruby on Rails']},
  {'user_id': 1430, 'user_stacks': ['PyTorch']},
  {'user_id': 1431, 'user_stacks': ['Kotlin', 'PHP', 'jQuery', 'PyTorch', 'Lua', 'Ruby', '.NET', 'Keras']},
  {'user_id': 1432, 'user_stacks': ['Python', 'PyTorch', 'Django', 'Qt', 'React Native', 'Blazor', 'Laravel', 'TensorFlow']},
  {'user_id': 1433, 'user_stacks': ['Ruby', 'jQuery', 'Go', 'C', 'Dart', 'React Native', 'Ruby on Rails', 'Pandas', 'Lua']},
  {'user_id': 1434, 'user_stacks': ['AngularJS', 'Express', 'TypeScript', 'Java', 'Blazor', 'JavaScript', 'RabbitMQ', 'Torch']},
  {'user_id': 1435, 'user_stacks': ['Electron', 'TensorFlow', 'SpringBoot']},
  {'user_id': 1436, 'user_stacks': ['jQuery', 'TypeScript', 'R', 'Rust', 'Svelte', 'scikit-Learn']},
  {'user_id': 1437, 'user_stacks': ['Vue.js', 'Angular', 'ASP.NET', 'React', 'C', 'NestJS', 'Kotlin', 'Laravel', 'Next.js']},
  {'user_id': 1438, 'user_stacks': ['Ruby', '.NET', 'ASP.NET']},
  {'user_id': 1439, 'user_stacks': ['Ruby on Rails', 'Torch', '.NET', 'OpenGL']},
  {'user_id': 1440, 'user_stacks': ['jQuery', 'Rust', 'Opencv', 'HTML/CSS', 'Java', 'Next.js', '.NET', 'ASP.NET', 'Ruby on Rails']},
  {'user_id': 1441, 'user_stacks': ['Java', 'Node.js', 'TypeScript', 'Pandas']},
  {'user_id': 1442, 'user_stacks': ['SpringBoot', 'Ruby', 'PHP']},
  {'user_id': 1443, 'user_stacks': ['C#', 'Flutter', 'AngularJS', 'Ruby', 'R', 'PyTorch', 'React Native', 'Express', 'Python', 'Svelte']},
  {'user_id': 1444, 'user_stacks': ['ASP.NET', 'Node.js', 'Electron']},
  {'user_id': 1445, 'user_stacks': ['Flask', 'AngularJS']},
  {'user_id': 1446, 'user_stacks': ['Django', 'Torch', 'Svelte', 'Dart', 'JavaScript', '.NET', 'PHP']},
  {'user_id': 1447, 'user_stacks': ['C++', 'Pandas', 'Laravel', 'R', 'React Native', 'AngularJS']},
  {'user_id': 1448, 'user_stacks': ['Laravel', 'Kotlin', 'Svelte', 'PHP', 'ASP.NET']},
  {'user_id': 1449, 'user_stacks': ['Go', 'Pandas', 'jQuery']},
  {'user_id': 1450, 'user_stacks': ['Dart', 'Torch', 'OpenGL', 'Flask', 'Qt', 'Blazor', 'SpringBoot']},
  {'user_id': 1451, 'user_stacks': ['Keras', 'Laravel']},
  {'user_id': 1452, 'user_stacks': ['Flutter', 'Electron', 'Flask', 'jQuery', 'PyTorch', 'Vue.js', '.NET', 'Apache Spark']},
  {'user_id': 1453, 'user_stacks': ['Opencv', 'Vue.js', 'React Native', 'OpenGL']},
  {'user_id': 1454, 'user_stacks': ['Electron', 'Vue.js', 'Laravel', 'TensorFlow', 'Lua', 'Express', 'JavaScript']},
  {'user_id': 1455, 'user_stacks': ['Laravel', 'HTML/CSS', 'Pandas', 'C', 'Vue.js', 'Apache Spark', 'C++', 'Qt']},
  {'user_id': 1456, 'user_stacks': ['Apache Spark', 'Qt', 'R', 'React', 'Dart', 'React Native', 'Keras', 'JavaScript']},
  {'user_id': 1457, 'user_stacks': ['jQuery', 'C#', 'React Native']},
  {'user_id': 1458, 'user_stacks': ['Pandas']},
  {'user_id': 1459, 'user_stacks': ['Angular', 'Qt']},
  {'user_id': 1460, 'user_stacks': ['React Native', 'scikit-Learn', '.NET', 'Laravel', 'Apache Spark', 'Flutter', 'Ruby', 'Ruby on Rails', 'React']},
  {'user_id': 1461, 'user_stacks': ['R', 'Next.js', 'TypeScript', 'C', 'Blazor']},
  {'user_id': 1462, 'user_stacks': ['Lua', 'Kotlin', 'PHP', 'ASP.NET', 'C', 'Vue.js', 'TensorFlow', 'C++', 'Flask']},
  {'user_id': 1463, 'user_stacks': ['React Native', 'RabbitMQ', 'OpenGL']},
  {'user_id': 1464, 'user_stacks': ['Blazor', 'Node.js', 'Express', 'RabbitMQ', 'R', 'C', 'Lua', 'Electron', 'React']},
  {'user_id': 1465, 'user_stacks': ['Vue.js', 'Angular', 'Pandas', 'ASP.NET']},
  {'user_id': 1466, 'user_stacks': ['Torch', 'AngularJS', '.NET', 'Django', 'React']},
  {'user_id': 1467, 'user_stacks': ['NestJS']},
  {'user_id': 1468, 'user_stacks': ['AngularJS', 'Lua', 'Kotlin']},
  {'user_id': 1469, 'user_stacks': ['Express', 'R', 'JavaScript', 'C++', 'ASP.NET', 'Vue.js']},
  {'user_id': 1470, 'user_stacks': ['Ruby', 'Python', 'Go', 'Java', 'Flask', 'OpenGL', 'Electron', 'Flutter']},
  {'user_id': 1471, 'user_stacks': ['Svelte', 'C#', 'Lua']},
  {'user_id': 1472, 'user_stacks': ['Go', 'Qt', 'Rust', 'SwiftUI']},
  {'user_id': 1473, 'user_stacks': ['RabbitMQ', 'Next.js', 'Opencv', 'Qt', 'R', 'Dart', 'Java', 'Laravel']},
  {'user_id': 1474, 'user_stacks': ['Pandas', 'TensorFlow', 'Qt', 'Flutter']},
  {'user_id': 1475, 'user_stacks': ['HTML/CSS', 'Node.js', 'Svelte', 'TensorFlow']},
  {'user_id': 1476, 'user_stacks': ['Swift', 'React Native', 'TensorFlow', 'Dart', '.NET', 'JavaScript', 'Torch']},
  {'user_id': 1477, 'user_stacks': ['Keras', 'PHP', 'Flask', 'AngularJS', 'RabbitMQ', 'Go', 'Ruby']},
  {'user_id': 1478, 'user_stacks': ['PyTorch', '.NET']},
  {'user_id': 1479, 'user_stacks': ['Python', 'SwiftUI', 'Pandas', 'Apache Spark', 'Swift', 'Svelte', 'C++', '.NET']},
  {'user_id': 1480, 'user_stacks': ['TensorFlow', 'Angular', 'Vue.js', 'TypeScript', 'JavaScript', 'Rust', 'Ruby']},
  {'user_id': 1481, 'user_stacks': ['Swift', 'TypeScript', 'NestJS', 'Torch', 'C++', 'Opencv', 'Electron', 'Pandas', 'Apache Spark', 'PHP']},
  {'user_id': 1482, 'user_stacks': ['C++', 'SwiftUI', 'JavaScript', 'Kotlin', 'React Native', 'Rust', 'jQuery', 'Django']},
  {'user_id': 1483, 'user_stacks': ['Go', 'C#', 'Django', '.NET', 'C', 'React Native', 'HTML/CSS', 'C++']},
  {'user_id': 1484, 'user_stacks': ['React Native', 'Opencv', 'Swift', 'OpenGL', '.NET']},
  {'user_id': 1485, 'user_stacks': ['Kotlin', 'SwiftUI', 'Swift', '.NET', 'PyTorch', 'Pandas', 'Laravel']},
  {'user_id': 1486, 'user_stacks': ['C++']},
  {'user_id': 1487, 'user_stacks': ['Electron', 'React Native', 'C#', 'Ruby on Rails', 'Flutter', 'Python', 'jQuery']},
  {'user_id': 1488, 'user_stacks': ['C++', 'Dart', 'Node.js', 'Laravel', 'Swift']},
  {'user_id': 1489, 'user_stacks': ['Dart', 'Flutter', 'Next.js']},
  {'user_id': 1490, 'user_stacks': ['Opencv', 'Flutter', 'Ruby']},
  {'user_id': 1491, 'user_stacks': ['Lua', 'Torch', 'Express']},
  {'user_id': 1492, 'user_stacks': ['Laravel', 'C++', 'TensorFlow']},
  {'user_id': 1493, 'user_stacks': ['Next.js']},
  {'user_id': 1494, 'user_stacks': ['jQuery', 'Express', 'Angular', 'Rust', 'PHP', 'Next.js', 'Dart', 'SpringBoot', 'Python', 'R']},
  {'user_id': 1495, 'user_stacks': ['jQuery', '.NET', 'Ruby on Rails', 'React Native', 'Kotlin', 'Lua', 'Svelte', 'TensorFlow']},
  {'user_id': 1496, 'user_stacks': ['Electron', 'Svelte', 'Torch', 'SwiftUI', 'Flask', 'Django', 'Express', 'Laravel', 'PHP', 'JavaScript']},
  {'user_id': 1497, 'user_stacks': ['C#', 'Go', 'SpringBoot']},
  {'user_id': 1498, 'user_stacks': ['React', 'Django', 'C#', 'Keras', 'Lua', 'Angular', 'Electron', 'PyTorch', 'C', 'Express']},
  {'user_id': 1499, 'user_stacks': ['TensorFlow', 'scikit-Learn', 'AngularJS', 'Pandas', 'R', 'OpenGL', 'Keras', 'Kotlin', '.NET']},
  {'user_id': 1500, 'user_stacks': ['Ruby', 'Electron', 'Flutter', 'Java', 'Svelte', 'jQuery', 'React']},
  {'user_id': 1501, 'user_stacks': ['OpenGL', 'Apache Spark', 'Python', 'Go', 'Django']},
  {'user_id': 1502, 'user_stacks': ['Qt', 'Svelte', 'SpringBoot', 'Lua', 'Node.js', 'Flask', 'React', 'Laravel', 'PyTorch', 'RabbitMQ']},
  {'user_id': 1503, 'user_stacks': ['Kotlin', 'Django']},
  {'user_id': 1504, 'user_stacks': ['Next.js', 'JavaScript']},
  {'user_id': 1505, 'user_stacks': ['Go', 'Svelte', 'Node.js', 'C#', 'Pandas', 'Angular', 'Qt', 'SpringBoot', 'Python']},
  {'user_id': 1506, 'user_stacks': ['R', 'HTML/CSS', 'Vue.js', 'Svelte', 'Python', 'Swift', 'OpenGL']},
  {'user_id': 1507, 'user_stacks': ['Electron', 'Keras', 'Flask', 'C#', 'Qt']},
  {'user_id': 1508, 'user_stacks': ['Vue.js', 'Express', 'Java', 'Flutter', 'Lua']},
  {'user_id': 1509, 'user_stacks': ['Dart', 'jQuery', 'Angular', 'TensorFlow', 'NestJS', 'Svelte', 'Express']},
  {'user_id': 1510, 'user_stacks': ['scikit-Learn', 'Torch', 'NestJS', 'Qt']},
  {'user_id': 1511, 'user_stacks': ['PyTorch', 'scikit-Learn', 'SwiftUI']},
  {'user_id': 1512, 'user_stacks': ['Rust', 'Swift', 'jQuery', 'Laravel', 'Python', 'Kotlin', 'AngularJS', 'Electron', 'Java']},
  {'user_id': 1513, 'user_stacks': ['Lua', 'Node.js', 'PHP', 'NestJS', 'Python', 'Laravel', 'Svelte']},
  {'user_id': 1514, 'user_stacks': ['RabbitMQ', 'Qt', 'Electron', 'Lua']},
  {'user_id': 1515, 'user_stacks': ['Python', 'Pandas', 'Next.js', 'C++', 'JavaScript', 'Node.js', 'C#', 'TypeScript', 'R']},
  {'user_id': 1516, 'user_stacks': ['TypeScript', 'Go', 'Python', 'scikit-Learn']},
  {'user_id': 1517, 'user_stacks': ['Ruby on Rails', 'Lua', 'RabbitMQ', 'Kotlin', 'React', 'Apache Spark', 'Node.js']},
  {'user_id': 1518, 'user_stacks': ['Django', 'Vue.js', 'Flask', 'React Native', 'PHP', 'Svelte', 'Keras']},
  {'user_id': 1519, 'user_stacks': ['Svelte']},
  {'user_id': 1520, 'user_stacks': ['.NET']},
  {'user_id': 1521, 'user_stacks': ['Flutter', 'Lua']},
  {'user_id': 1522, 'user_stacks': ['Go']},
  {'user_id': 1523, 'user_stacks': ['OpenGL', 'scikit-Learn', 'Kotlin', 'Svelte', 'Qt', 'PHP', 'HTML/CSS', 'Flutter']},
  {'user_id': 1524, 'user_stacks': ['Next.js', 'Kotlin', 'React Native', 'C', 'OpenGL']},
  {'user_id': 1525, 'user_stacks': ['SwiftUI', 'Laravel', 'JavaScript', 'React', 'Pandas', 'jQuery', 'HTML/CSS', 'RabbitMQ', 'Kotlin']},
  {'user_id': 1526, 'user_stacks': ['React Native', 'Lua', 'SpringBoot', 'JavaScript', 'Opencv', 'C#', 'TensorFlow', 'ASP.NET', 'C']},
  {'user_id': 1527, 'user_stacks': ['JavaScript', 'Dart', 'Svelte', 'Python']},
  {'user_id': 1528, 'user_stacks': ['HTML/CSS', 'Python', 'Pandas']},
  {'user_id': 1529, 'user_stacks': ['Ruby on Rails', 'NestJS', 'Torch', 'Python', 'OpenGL', 'C', 'Apache Spark', 'Flask']},
  {'user_id': 1530, 'user_stacks': ['Torch', 'Qt', 'RabbitMQ', 'SwiftUI']},
  {'user_id': 1531, 'user_stacks': ['Swift', 'Next.js', 'C#', 'NestJS', 'R', 'AngularJS', 'HTML/CSS', 'Flask', 'TypeScript']},
  {'user_id': 1532, 'user_stacks': ['Keras', 'Flask', 'Electron', 'Apache Spark', 'RabbitMQ', 'Ruby on Rails', 'Kotlin', 'C++', 'Express', 'PHP']},
  {'user_id': 1533, 'user_stacks': ['SpringBoot']},
  {'user_id': 1534, 'user_stacks': ['Laravel', 'TypeScript', 'Blazor', 'TensorFlow', 'Express']},
  {'user_id': 1535, 'user_stacks': ['AngularJS', 'PyTorch', 'Angular', 'Qt', 'C++', 'C', 'RabbitMQ']},
  {'user_id': 1536, 'user_stacks': ['Pandas', 'HTML/CSS', 'Express', 'Node.js', 'jQuery', 'TypeScript', 'Dart', 'Java', 'Vue.js', 'Electron']},
  {'user_id': 1537, 'user_stacks': ['C++', 'jQuery', 'React Native', 'C#', 'Django', 'Laravel', 'JavaScript', 'Angular']},
  {'user_id': 1538, 'user_stacks': ['Lua', 'React Native', 'RabbitMQ', 'PyTorch', 'PHP', 'SwiftUI', 'TensorFlow', 'SpringBoot', 'Express']},
  {'user_id': 1539, 'user_stacks': ['Electron', 'Keras', 'Blazor', 'C#', 'Flask', 'Node.js']},
  {'user_id': 1540, 'user_stacks': ['Blazor']},
  {'user_id': 1541, 'user_stacks': ['AngularJS']},
  {'user_id': 1542, 'user_stacks': ['OpenGL', 'Express', 'Keras', 'Flutter', 'HTML/CSS', 'PyTorch', '.NET', 'Swift', 'Rust', 'SwiftUI']},
  {'user_id': 1543, 'user_stacks': ['Angular', 'React', 'React Native', 'Rust', 'Apache Spark', 'Django', 'Flutter', 'C++', 'Express', 'Python']},
  {'user_id': 1544, 'user_stacks': ['Rust', 'SwiftUI']},
  {'user_id': 1545, 'user_stacks': ['SpringBoot', 'NestJS', 'HTML/CSS', 'PyTorch', 'Flutter', 'Next.js']},
  {'user_id': 1546, 'user_stacks': ['R', 'SwiftUI', 'Qt', 'jQuery', 'Next.js', 'Torch', 'NestJS', 'HTML/CSS', 'C']},
  {'user_id': 1547, 'user_stacks': ['Dart', 'jQuery', 'Blazor', 'Qt', 'Apache Spark', 'Python']},
  {'user_id': 1548, 'user_stacks': ['R', 'Qt']},
  {'user_id': 1549, 'user_stacks': ['Ruby on Rails', 'Lua', 'Angular', 'Apache Spark', '.NET', 'Laravel', 'PyTorch']},
  {'user_id': 1550, 'user_stacks': ['Torch', 'Qt', 'Vue.js', 'NestJS', 'Node.js', 'scikit-Learn', 'PHP', 'Opencv', 'Flask']},
  {'user_id': 1551, 'user_stacks': ['Flutter', 'Ruby on Rails', 'Next.js', 'Keras', 'React']},
  {'user_id': 1552, 'user_stacks': ['R', 'ASP.NET', 'Kotlin', 'C#', 'C++', 'Opencv', 'Qt']},
  {'user_id': 1553, 'user_stacks': ['SpringBoot', 'Laravel', 'TensorFlow']},
  {'user_id': 1554, 'user_stacks': ['Node.js', 'Blazor']},
  {'user_id': 1555, 'user_stacks': ['RabbitMQ', 'Flutter']},
  {'user_id': 1556, 'user_stacks': ['NestJS', 'Python', 'C++', 'Opencv', 'Django', 'Keras', 'Torch', 'Laravel', 'JavaScript']},
  {'user_id': 1557, 'user_stacks': ['Ruby']},
  {'user_id': 1558, 'user_stacks': ['TypeScript', 'Torch', 'NestJS', 'Apache Spark', 'R', 'Dart', 'Opencv', 'Java', 'PHP', 'C']},
  {'user_id': 1559, 'user_stacks': ['C++', 'C', 'Swift', 'Electron', '.NET', 'Django', 'C#']},
  {'user_id': 1560, 'user_stacks': ['Node.js', 'Vue.js', 'React Native', 'Opencv', 'RabbitMQ', 'SpringBoot', 'Svelte', 'Ruby on Rails', 'TensorFlow']},
  {'user_id': 1561, 'user_stacks': ['Vue.js', 'OpenGL', 'AngularJS', 'Pandas']},
  {'user_id': 1562, 'user_stacks': ['Ruby', 'Java', 'jQuery', 'TypeScript', 'HTML/CSS', '.NET', 'C++']},
  {'user_id': 1563, 'user_stacks': ['Keras', 'JavaScript', 'Rust', 'Flutter', 'TensorFlow', 'Apache Spark']},
  {'user_id': 1564, 'user_stacks': ['scikit-Learn', 'PyTorch', 'Next.js', 'SwiftUI', 'React', 'SpringBoot', 'Lua']},
  {'user_id': 1565, 'user_stacks': ['TypeScript', 'SpringBoot', 'Python', 'RabbitMQ', 'HTML/CSS', 'Vue.js', 'React Native']},
  {'user_id': 1566, 'user_stacks': ['HTML/CSS', 'ASP.NET', 'Next.js']},
  {'user_id': 1567, 'user_stacks': ['AngularJS', 'Vue.js', 'Rust', 'SpringBoot', 'JavaScript', 'RabbitMQ', 'Angular', 'PyTorch', 'Django']},
  {'user_id': 1568, 'user_stacks': ['scikit-Learn', 'Swift', 'Flutter']},
  {'user_id': 1569, 'user_stacks': ['NestJS']},
  {'user_id': 1570, 'user_stacks': ['Opencv', 'Pandas']},
  {'user_id': 1571, 'user_stacks': ['Dart', 'Keras', 'jQuery', 'RabbitMQ', 'Flask', 'SwiftUI', 'TensorFlow', 'ASP.NET']},
  {'user_id': 1572, 'user_stacks': ['Lua', 'React', 'Pandas', 'Node.js', 'C++', 'Qt', 'Svelte']},
  {'user_id': 1573, 'user_stacks': ['Blazor', 'Keras', 'Next.js', 'Swift']},
  {'user_id': 1574, 'user_stacks': ['jQuery', 'Apache Spark', 'SpringBoot', 'scikit-Learn']},
  {'user_id': 1575, 'user_stacks': ['Dart', 'Laravel', 'React Native', 'AngularJS', 'Angular', 'PyTorch']},
  {'user_id': 1576, 'user_stacks': ['Next.js', 'Qt', '.NET']},
  {'user_id': 1577, 'user_stacks': ['Go', 'Python', 'Torch']},
  {'user_id': 1578, 'user_stacks': ['Express']},
  {'user_id': 1579, 'user_stacks': ['TypeScript', 'C#', 'Opencv', 'C++', 'Flask']},
  {'user_id': 1580, 'user_stacks': ['Express', 'HTML/CSS', 'Next.js', 'PHP', 'Opencv', 'TensorFlow', 'Apache Spark']},
  {'user_id': 1581, 'user_stacks': ['Flask', 'SpringBoot', 'jQuery', 'Kotlin', 'SwiftUI', 'Ruby on Rails']},
  {'user_id': 1582, 'user_stacks': ['scikit-Learn', 'React', 'Swift', 'Keras', 'Pandas', 'SpringBoot', 'NestJS', 'Kotlin', 'Laravel']},
  {'user_id': 1583, 'user_stacks': ['ASP.NET', 'AngularJS', 'R', 'Torch', 'React', 'Next.js', 'C#', 'PyTorch']},
  {'user_id': 1584, 'user_stacks': ['Kotlin', 'PyTorch', 'Svelte', 'Blazor']},
  {'user_id': 1585, 'user_stacks': ['Electron', 'JavaScript', 'Keras', 'Svelte', 'Node.js']},
  {'user_id': 1586, 'user_stacks': ['NestJS', 'Kotlin', 'AngularJS', 'Python']},
  {'user_id': 1587, 'user_stacks': ['C#', 'RabbitMQ', 'Python', 'Rust', 'HTML/CSS', 'Pandas', '.NET', 'Svelte', 'Apache Spark', 'Torch']},
  {'user_id': 1588, 'user_stacks': ['Django', 'ASP.NET', 'SpringBoot', 'Apache Spark', 'Flask', 'PHP']},
  {'user_id': 1589, 'user_stacks': ['OpenGL', 'ASP.NET', 'jQuery', 'Django', 'Dart']},
  {'user_id': 1590, 'user_stacks': ['Keras', 'Django', 'Node.js', 'HTML/CSS', 'Svelte']},
  {'user_id': 1591, 'user_stacks': ['Kotlin', 'Rust']},
  {'user_id': 1592, 'user_stacks': ['Keras', 'AngularJS', 'Go', 'Ruby', 'JavaScript', 'React Native', 'Pandas', 'React', 'C#']},
  {'user_id': 1593, 'user_stacks': ['PHP', 'Next.js', 'React Native', 'OpenGL']},
  {'user_id': 1594, 'user_stacks': ['Java', 'Opencv', 'JavaScript', 'Apache Spark']},
  {'user_id': 1595, 'user_stacks': ['PHP', 'Swift']},
  {'user_id': 1596, 'user_stacks': ['Vue.js', 'ASP.NET', 'Keras', 'Blazor', 'Ruby on Rails']},
  {'user_id': 1597, 'user_stacks': ['React', 'Laravel', 'PHP', 'PyTorch', 'Express', 'SpringBoot', 'Dart', 'HTML/CSS', 'Flask', 'scikit-Learn']},
  {'user_id': 1598, 'user_stacks': ['PHP', 'C++', 'Java', 'Django', 'Electron', 'Swift', 'PyTorch', 'Opencv', 'C#', 'HTML/CSS']},
  {'user_id': 1599, 'user_stacks': ['Apache Spark', 'Flask', 'Opencv', 'Svelte', 'Ruby on Rails', 'PHP', 'C++', 'Next.js', '.NET']},
  {'user_id': 1600, 'user_stacks': ['SpringBoot', 'Next.js', 'Torch']},
  {'user_id': 1601, 'user_stacks': ['Kotlin', 'C++', 'Ruby on Rails', 'Svelte', 'jQuery', 'C', 'Electron', 'ASP.NET', 'Angular', 'TypeScript']},
  {'user_id': 1602, 'user_stacks': ['Node.js', 'Torch', 'ASP.NET', 'Rust', 'NestJS', 'Qt']},
  {'user_id': 1603, 'user_stacks': ['Svelte', 'NestJS', 'PyTorch', 'Apache Spark', 'Keras', 'Go', 'R', 'Electron', 'Lua', 'Swift']},
  {'user_id': 1604, 'user_stacks': ['Svelte', 'Java', 'OpenGL', 'Ruby', 'R', 'Electron', 'jQuery', 'Dart', 'JavaScript']},
  {'user_id': 1605, 'user_stacks': ['HTML/CSS', 'Torch', 'C', 'C++', 'PHP', 'Qt']},
  {'user_id': 1606, 'user_stacks': ['ASP.NET', 'Ruby on Rails', 'RabbitMQ', 'Node.js', 'HTML/CSS', 'Torch']},
  {'user_id': 1607, 'user_stacks': ['Lua', 'HTML/CSS', 'Node.js', 'Go', 'Python']},
  {'user_id': 1608, 'user_stacks': ['React Native', 'React', 'Electron', 'SwiftUI', 'Blazor']},
  {'user_id': 1609, 'user_stacks': ['Torch', 'Blazor', 'Vue.js']},
  {'user_id': 1610, 'user_stacks': ['RabbitMQ']},
  {'user_id': 1611, 'user_stacks': ['OpenGL', 'Python', 'ASP.NET', 'Node.js', 'TensorFlow', 'Go', 'Dart', 'HTML/CSS', 'SpringBoot', 'Django']},
  {'user_id': 1612, 'user_stacks': ['Apache Spark', 'HTML/CSS', 'C', 'Laravel', 'SpringBoot', 'Dart', 'Svelte', 'Flutter', 'Lua', 'Kotlin']},
  {'user_id': 1613, 'user_stacks': ['R', '.NET', 'Kotlin']},
  {'user_id': 1614, 'user_stacks': ['Dart', 'Go', 'TypeScript', 'RabbitMQ', 'Qt', 'C++', 'Rust']},
  {'user_id': 1615, 'user_stacks': ['Express', 'Torch', 'Vue.js', 'SpringBoot', 'TensorFlow', 'Lua']},
  {'user_id': 1616, 'user_stacks': ['SpringBoot', 'Lua', 'Ruby on Rails', 'OpenGL', 'Swift']},
  {'user_id': 1617, 'user_stacks': ['TypeScript', 'React Native', 'Node.js', 'SpringBoot', 'HTML/CSS']},
  {'user_id': 1618, 'user_stacks': ['Laravel', 'C++', 'React Native']},
  {'user_id': 1619, 'user_stacks': ['TensorFlow', 'SpringBoot', 'scikit-Learn', 'AngularJS', 'JavaScript']},
  {'user_id': 1620, 'user_stacks': ['RabbitMQ', 'React Native', 'C++', 'Opencv', 'TypeScript', 'Express']},
  {'user_id': 1621, 'user_stacks': ['jQuery', 'Node.js', 'Angular']},
  {'user_id': 1622, 'user_stacks': ['Opencv', 'Ruby on Rails', 'Flutter', 'TensorFlow']},
  {'user_id': 1623, 'user_stacks': ['React', 'Electron', 'Flask', 'Ruby', 'SpringBoot', 'Pandas', 'Ruby on Rails', 'NestJS']},
  {'user_id': 1624, 'user_stacks': ['Python', 'Pandas', 'TensorFlow', 'Flutter', 'SwiftUI', 'Blazor', 'C#']},
  {'user_id': 1625, 'user_stacks': ['C#', 'Django']},
  {'user_id': 1626, 'user_stacks': ['Python', 'JavaScript', 'OpenGL', 'Go']},
  {'user_id': 1627, 'user_stacks': ['Java', 'Angular', 'Express', 'RabbitMQ']},
  {'user_id': 1628, 'user_stacks': ['HTML/CSS', 'Ruby on Rails', 'Go', 'SwiftUI', 'Rust', 'Dart', 'Blazor']},
  {'user_id': 1629, 'user_stacks': ['JavaScript', 'RabbitMQ']},
  {'user_id': 1630, 'user_stacks': ['Electron', 'PHP', 'TypeScript']},
  {'user_id': 1631, 'user_stacks': ['HTML/CSS', 'Django', 'React']},
  {'user_id': 1632, 'user_stacks': ['RabbitMQ', 'AngularJS', 'Express', 'Go', 'Flask', 'Vue.js', 'C', 'Kotlin', 'Node.js', 'NestJS']},
  {'user_id': 1633, 'user_stacks': ['Lua', 'Blazor', 'TypeScript', 'AngularJS', 'ASP.NET', 'Rust', 'Torch']},
  {'user_id': 1634, 'user_stacks': ['Dart', 'Ruby', 'Next.js', 'Angular', 'React Native', 'Vue.js', 'Flask', 'SwiftUI', 'TypeScript']},
  {'user_id': 1635, 'user_stacks': ['ASP.NET', 'NestJS', 'Ruby on Rails', 'Dart', 'SpringBoot', 'R', 'Node.js', 'C', 'Opencv']},
  {'user_id': 1636, 'user_stacks': ['NestJS', 'TensorFlow', 'Vue.js', 'Angular']},
  {'user_id': 1637, 'user_stacks': ['Django', 'RabbitMQ', 'HTML/CSS', 'Rust', 'PHP', 'Node.js', 'ASP.NET', 'SwiftUI']},
  {'user_id': 1638, 'user_stacks': ['PHP']},
  {'user_id': 1639, 'user_stacks': ['Flask', 'Django', 'React']},
  {'user_id': 1640, 'user_stacks': ['Lua', 'Python', 'Vue.js', 'Django', 'TensorFlow', 'Rust', 'Blazor', 'Electron']},
  {'user_id': 1641, 'user_stacks': ['Laravel', 'NestJS', 'RabbitMQ', 'Vue.js', 'C++', 'HTML/CSS', 'jQuery', 'PyTorch', 'React']},
  {'user_id': 1642, 'user_stacks': ['Ruby on Rails', 'RabbitMQ', 'C++', 'Ruby', 'Svelte', 'Blazor']},
  {'user_id': 1643, 'user_stacks': ['PyTorch', 'Electron', 'AngularJS', 'Python', 'OpenGL', 'Express', 'Laravel', 'HTML/CSS']},
  {'user_id': 1644, 'user_stacks': ['SwiftUI', 'jQuery', 'React Native', 'scikit-Learn', 'SpringBoot', 'Python', 'C++', 'PHP']},
  {'user_id': 1645, 'user_stacks': ['React Native', 'C++', 'NestJS']},
  {'user_id': 1646, 'user_stacks': ['HTML/CSS', 'Flutter', 'Svelte', 'Flask', 'Keras', 'Torch', 'ASP.NET', 'Java', 'RabbitMQ']},
  {'user_id': 1647, 'user_stacks': ['SpringBoot', 'C', 'TypeScript', 'Lua', 'Kotlin', 'Rust']},
  {'user_id': 1648, 'user_stacks': ['Ruby on Rails', '.NET', 'Svelte', 'Apache Spark', 'C#', 'R', 'Next.js']},
  {'user_id': 1649, 'user_stacks': ['Torch', 'TypeScript', 'jQuery', 'Flutter', 'SwiftUI', 'Rust', 'HTML/CSS', 'ASP.NET', 'Express', 'C++']},
  {'user_id': 1650, 'user_stacks': ['Qt', 'Swift', 'C++', 'HTML/CSS', 'PyTorch', 'OpenGL', 'Dart']},
  {'user_id': 1651, 'user_stacks': ['Vue.js', 'Flask', 'Svelte', 'Apache Spark', 'Swift', 'Next.js']},
  {'user_id': 1652, 'user_stacks': ['SwiftUI', 'Angular']},
  {'user_id': 1653, 'user_stacks': ['R']},
  {'user_id': 1654, 'user_stacks': ['Kotlin', 'Django', 'TypeScript', 'Pandas', 'Next.js', 'PHP', 'Svelte']},
  {'user_id': 1655, 'user_stacks': ['SpringBoot', 'C', 'NestJS']},
  {'user_id': 1656, 'user_stacks': ['Swift', 'Pandas', 'Flutter']},
  {'user_id': 1657, 'user_stacks': ['Flask']},
  {'user_id': 1658, 'user_stacks': ['Python', 'Ruby', 'Svelte', 'PHP', 'SpringBoot', 'Blazor', 'Flutter', 'C#', 'React', 'Next.js']},
  {'user_id': 1659, 'user_stacks': ['.NET', 'Keras', 'R', 'Torch', 'Django']},
  {'user_id': 1660, 'user_stacks': ['jQuery', 'Keras']},
  {'user_id': 1661, 'user_stacks': ['Apache Spark', 'SwiftUI']},
  {'user_id': 1662, 'user_stacks': ['Node.js', 'TypeScript', 'RabbitMQ']},
  {'user_id': 1663, 'user_stacks': ['Svelte', 'scikit-Learn', 'Next.js', 'Keras', 'TypeScript', 'SwiftUI', 'Python', 'PyTorch', 'ASP.NET', 'C#']},
  {'user_id': 1664, 'user_stacks': ['R', 'Django', 'Swift', 'scikit-Learn', 'Blazor', 'C', 'Flask', 'ASP.NET', 'SwiftUI', 'C#']},
  {'user_id': 1665, 'user_stacks': ['Django', 'Express', 'OpenGL', 'SpringBoot', 'PHP']},
  {'user_id': 1666, 'user_stacks': ['Node.js', 'C']},
  {'user_id': 1667, 'user_stacks': ['Node.js', 'R', 'HTML/CSS', 'Dart', 'Angular']},
  {'user_id': 1668, 'user_stacks': ['C', 'AngularJS', 'Angular', 'React', 'Node.js', 'Rust', 'Swift']},
  {'user_id': 1669, 'user_stacks': ['SpringBoot', 'Swift', 'Next.js', 'Apache Spark', 'HTML/CSS', 'Pandas', 'Keras', 'Python', 'Dart']},
  {'user_id': 1670, 'user_stacks': ['Pandas', 'Python', 'Laravel', 'Dart', '.NET', 'Blazor', 'Keras', 'Java']},
  {'user_id': 1671, 'user_stacks': ['Laravel', 'ASP.NET', 'C++']},
  {'user_id': 1672, 'user_stacks': ['Django', 'Qt', 'Blazor', 'Go', 'AngularJS', 'Node.js', 'Next.js']},
  {'user_id': 1673, 'user_stacks': ['Flask', 'Pandas', 'Java', 'Blazor', 'AngularJS', 'Node.js', 'Electron', 'Vue.js', 'PHP']},
  {'user_id': 1674, 'user_stacks': ['R', 'HTML/CSS', 'ASP.NET', 'Dart', 'OpenGL', 'Flask', 'Opencv', 'SwiftUI']},
  {'user_id': 1675, 'user_stacks': ['Python', 'C', 'Flutter', 'AngularJS', 'TypeScript', 'Svelte', 'React', 'Electron', 'Go', 'JavaScript']},
  {'user_id': 1676, 'user_stacks': ['Apache Spark', 'RabbitMQ', 'Pandas', 'ASP.NET', 'NestJS', 'Node.js', 'Swift', 'Dart']},
  {'user_id': 1677, 'user_stacks': ['PyTorch', 'Svelte', 'SpringBoot', 'Angular', 'Node.js', 'Laravel']},
  {'user_id': 1678, 'user_stacks': ['Lua', 'PHP', 'Node.js', 'Pandas', 'React', 'Flask', 'Laravel']},
  {'user_id': 1679, 'user_stacks': ['Lua', 'Angular']},
  {'user_id': 1680, 'user_stacks': ['Django', 'scikit-Learn', 'Lua', 'Kotlin', 'Swift', 'Flutter', 'jQuery', 'SwiftUI', 'Svelte', '.NET']},
  {'user_id': 1681, 'user_stacks': ['Express', 'Angular', 'Rust', 'Lua', 'Vue.js', '.NET', 'TypeScript', 'HTML/CSS', 'Ruby on Rails', 'OpenGL']},
  {'user_id': 1682, 'user_stacks': ['Vue.js', 'SwiftUI', 'C#', 'Java', 'Keras', 'Kotlin']},
  {'user_id': 1683, 'user_stacks': ['Kotlin', 'Qt', 'Blazor', 'Torch', 'Dart']},
  {'user_id': 1684, 'user_stacks': ['TypeScript']},
  {'user_id': 1685, 'user_stacks': ['React Native']},
  {'user_id': 1686, 'user_stacks': ['C', 'Qt', 'Angular', 'Flask', 'Kotlin', 'Next.js']},
  {'user_id': 1687, 'user_stacks': ['Lua']},
  {'user_id': 1688, 'user_stacks': ['Electron', 'SpringBoot', 'Svelte']},
  {'user_id': 1689, 'user_stacks': ['React', 'jQuery', 'Go', 'Torch', 'Flask', 'Express', 'PHP', 'Keras', 'C']},
  {'user_id': 1690, 'user_stacks': ['Flutter', 'Pandas', 'Node.js', 'C++', 'Ruby', 'Apache Spark', 'RabbitMQ']},
  {'user_id': 1691, 'user_stacks': ['Opencv', 'Kotlin', 'scikit-Learn', 'Pandas', 'Next.js', 'Torch', 'Go', 'React Native', 'Qt', 'TensorFlow']},
  {'user_id': 1692, 'user_stacks': ['HTML/CSS', 'C#', 'Opencv', 'Qt', 'Torch', 'Node.js', 'Flask']},
  {'user_id': 1693, 'user_stacks': ['Rust', 'C#', 'React Native', 'OpenGL', 'Go', 'Java', 'Flask', 'Opencv', 'Svelte']},
  {'user_id': 1694, 'user_stacks': ['Dart', 'TensorFlow', 'Go', 'Ruby', 'Vue.js', 'AngularJS', 'Rust', 'jQuery', 'RabbitMQ', 'C++']},
  {'user_id': 1695, 'user_stacks': ['Apache Spark', 'RabbitMQ', '.NET', 'PyTorch', 'TensorFlow', 'Keras', 'Ruby on Rails']},
  {'user_id': 1696, 'user_stacks': ['React Native']},
  {'user_id': 1697, 'user_stacks': ['Torch', 'TensorFlow', 'Express', 'Python']},
  {'user_id': 1698, 'user_stacks': ['Dart', 'C', 'React Native', 'Java', 'Next.js']},
  {'user_id': 1699, 'user_stacks': ['Next.js', 'Torch', 'Svelte', 'Express', 'SwiftUI', 'ASP.NET', 'scikit-Learn', '.NET', 'AngularJS']},
  {'user_id': 1700, 'user_stacks': ['Ruby', 'Opencv', 'Torch', 'SpringBoot', 'TensorFlow', 'HTML/CSS', 'C#', 'TypeScript', 'SwiftUI', 'PHP']},
  {'user_id': 1701, 'user_stacks': ['Go', 'Blazor', 'SpringBoot', 'Pandas', 'Lua', 'React']},
  {'user_id': 1702, 'user_stacks': ['JavaScript', 'Electron', 'C#', 'SpringBoot']},
  {'user_id': 1703, 'user_stacks': ['Flutter', 'Ruby', 'SpringBoot']},
  {'user_id': 1704, 'user_stacks': ['Ruby', 'OpenGL', 'Django', 'JavaScript', 'Qt', 'Kotlin']},
  {'user_id': 1705, 'user_stacks': ['Django', 'HTML/CSS', 'SpringBoot', 'SwiftUI', 'Flask', 'RabbitMQ', 'NestJS', 'Ruby on Rails', 'Keras']},
  {'user_id': 1706, 'user_stacks': ['PHP', 'Laravel', 'ASP.NET', 'Dart', 'Vue.js', 'Python', 'Qt', 'SpringBoot', 'TypeScript']},
  {'user_id': 1707, 'user_stacks': ['Lua', 'Next.js', 'Keras', 'Java', 'Vue.js', 'Electron', 'Pandas', 'Go']},
  {'user_id': 1708, 'user_stacks': ['Laravel', 'Svelte', 'Opencv']},
  {'user_id': 1709, 'user_stacks': ['Python', 'Electron', 'AngularJS', 'SpringBoot', 'Svelte', 'PyTorch', 'C++', 'TensorFlow']},
  {'user_id': 1710, 'user_stacks': ['NestJS', 'Go', 'React', 'C++', 'C', '.NET', 'Vue.js', 'JavaScript']},
  {'user_id': 1711, 'user_stacks': ['TypeScript', 'Apache Spark', 'Electron', 'Node.js', 'Flask', 'Laravel', 'Pandas', 'React']},
  {'user_id': 1712, 'user_stacks': ['ASP.NET', 'Pandas', 'AngularJS', 'Dart', 'NestJS', 'scikit-Learn', 'PyTorch']},
  {'user_id': 1713, 'user_stacks': ['Lua']},
  {'user_id': 1714, 'user_stacks': ['.NET', 'Ruby', 'AngularJS', 'SwiftUI', 'Lua', 'Svelte']},
  {'user_id': 1715, 'user_stacks': ['C#']},
  {'user_id': 1716, 'user_stacks': ['Ruby', 'TypeScript', 'AngularJS', 'Angular']},
  {'user_id': 1717, 'user_stacks': ['JavaScript', 'R', 'scikit-Learn', 'Torch', 'Ruby on Rails', 'Opencv', 'Swift', 'Ruby', 'SwiftUI', 'AngularJS']},
  {'user_id': 1718, 'user_stacks': ['Django', 'SpringBoot', 'Pandas', 'Swift', 'Python']},
  {'user_id': 1719, 'user_stacks': ['C#', 'React']},
  {'user_id': 1720, 'user_stacks': ['OpenGL', 'C++']},
  {'user_id': 1721, 'user_stacks': ['jQuery', 'Node.js', 'React', 'TensorFlow', 'Dart', 'Torch', 'Next.js', 'React Native', 'Apache Spark', 'AngularJS']},
  {'user_id': 1722, 'user_stacks': ['OpenGL']},
  {'user_id': 1723, 'user_stacks': ['RabbitMQ', 'Flutter', 'Dart', '.NET', 'Laravel', 'Torch', 'C++', 'JavaScript']},
  {'user_id': 1724, 'user_stacks': ['Lua', 'AngularJS', 'React']},
  {'user_id': 1725, 'user_stacks': ['Node.js', 'Flutter', 'scikit-Learn']},
  {'user_id': 1726, 'user_stacks': ['JavaScript', 'Node.js', 'Qt', 'React Native', 'Flutter']},
  {'user_id': 1727, 'user_stacks': ['Opencv', 'Torch', 'Flutter', 'jQuery']},
  {'user_id': 1728, 'user_stacks': ['.NET', 'PHP', 'C#', 'NestJS', 'AngularJS']},
  {'user_id': 1729, 'user_stacks': ['React', 'Blazor']},
  {'user_id': 1730, 'user_stacks': ['Opencv', 'Apache Spark', 'TensorFlow']},
  {'user_id': 1731, 'user_stacks': ['NestJS', 'SwiftUI', 'Electron', 'Django', 'OpenGL', 'Lua', 'C++', 'Java', 'TypeScript']},
  {'user_id': 1732, 'user_stacks': ['Electron', 'Svelte', 'Swift', 'Lua', 'jQuery', 'Keras', 'ASP.NET', 'Torch', 'React Native']},
  {'user_id': 1733, 'user_stacks': ['Node.js', 'Blazor', 'scikit-Learn', 'C#', 'Lua']},
  {'user_id': 1734, 'user_stacks': ['SwiftUI', 'Pandas', 'Flask']},
  {'user_id': 1735, 'user_stacks': ['OpenGL', 'SpringBoot', 'NestJS', 'Kotlin', 'PyTorch', 'TensorFlow', 'Flask', 'RabbitMQ', 'HTML/CSS', 'Dart']},
  {'user_id': 1736, 'user_stacks': ['Flask', 'Python', 'Go', 'React', 'C++', 'HTML/CSS', 'Java', 'Next.js', 'Blazor', 'Rust']},
  {'user_id': 1737, 'user_stacks': ['Lua', 'Next.js', 'Torch', 'Pandas', 'ASP.NET', 'jQuery', 'NestJS', 'PyTorch', 'SpringBoot']},
  {'user_id': 1738, 'user_stacks': ['Flutter', 'SwiftUI', 'C#', 'Electron', 'Keras', 'Svelte', 'Go', 'SpringBoot', 'Next.js']},
  {'user_id': 1739, 'user_stacks': ['HTML/CSS', 'Rust', 'RabbitMQ', 'Node.js', 'Kotlin', 'R', 'TypeScript', 'jQuery', 'Opencv', 'Python']},
  {'user_id': 1740, 'user_stacks': ['AngularJS', 'Apache Spark', 'Angular', 'scikit-Learn', 'Opencv', 'HTML/CSS', 'Express']},
  {'user_id': 1741, 'user_stacks': ['SwiftUI', 'Ruby on Rails', 'React', 'Ruby', 'Django', 'Java', 'Pandas']},
  {'user_id': 1742, 'user_stacks': ['Torch', 'Next.js', 'Rust', 'Laravel', 'SwiftUI', 'Flutter', 'Svelte', 'TensorFlow', 'Blazor', 'Java']},
  {'user_id': 1743, 'user_stacks': ['TypeScript', 'Qt']},
  {'user_id': 1744, 'user_stacks': ['Torch', 'TensorFlow', 'Vue.js', 'Java']},
  {'user_id': 1745, 'user_stacks': ['SpringBoot', 'Svelte', '.NET', 'React']},
  {'user_id': 1746, 'user_stacks': ['Node.js', 'OpenGL', 'Pandas', 'HTML/CSS', 'Lua', 'C#', 'RabbitMQ', 'SwiftUI', 'Blazor', 'Qt']},
  {'user_id': 1747, 'user_stacks': ['Svelte']},
  {'user_id': 1748, 'user_stacks': ['scikit-Learn', 'Rust', 'Swift', 'Node.js', 'Angular', 'Apache Spark']},
  {'user_id': 1749, 'user_stacks': ['HTML/CSS', 'OpenGL', 'SpringBoot', 'Swift', 'Lua', 'C#']},
  {'user_id': 1750, 'user_stacks': ['C', 'NestJS']},
  {'user_id': 1751, 'user_stacks': ['Node.js', 'jQuery', 'Qt', 'OpenGL', 'SwiftUI', 'Django', 'Express', 'Torch']},
  {'user_id': 1752, 'user_stacks': ['Qt', 'Flutter', 'JavaScript', 'C']},
  {'user_id': 1753, 'user_stacks': ['Opencv', 'TypeScript', 'Kotlin', 'Torch', 'jQuery', 'Ruby', 'NestJS', 'Swift', 'Rust']},
  {'user_id': 1754, 'user_stacks': ['C', 'Java', 'React Native', 'HTML/CSS', 'R', 'Python', 'Torch', 'Dart', 'NestJS', 'Angular']},
  {'user_id': 1755, 'user_stacks': ['Opencv', 'Ruby']},
  {'user_id': 1756, 'user_stacks': ['AngularJS', 'Rust', 'R', 'TypeScript', 'Python', 'Kotlin', 'Vue.js']},
  {'user_id': 1757, 'user_stacks': ['JavaScript', 'Flutter', 'ASP.NET', 'Python', 'PHP', 'Node.js', 'Electron', 'Go', 'Kotlin', 'Next.js']},
  {'user_id': 1758, 'user_stacks': ['Keras', 'C++', 'Rust', 'Go', 'Opencv']},
  {'user_id': 1759, 'user_stacks': ['Flask', 'C', 'Keras', 'Svelte', 'Laravel', 'Django', 'Java', 'Opencv', 'HTML/CSS', 'React Native']},
  {'user_id': 1760, 'user_stacks': ['AngularJS', 'Apache Spark', 'Opencv', 'PyTorch', 'C', 'Java', 'scikit-Learn', 'Ruby']},
  {'user_id': 1761, 'user_stacks': ['Ruby', 'C', 'Node.js']},
  {'user_id': 1762, 'user_stacks': ['Rust']},
  {'user_id': 1763, 'user_stacks': ['Ruby', 'Flask', 'Torch', 'Laravel', 'Kotlin', 'OpenGL']},
  {'user_id': 1764, 'user_stacks': ['Lua']},
  {'user_id': 1765, 'user_stacks': ['RabbitMQ', 'Flask', 'Node.js', 'R', 'Ruby on Rails']},
  {'user_id': 1766, 'user_stacks': ['Flutter', 'Kotlin', 'R', 'Flask', 'Ruby on Rails', 'SpringBoot', 'HTML/CSS', 'RabbitMQ', 'Svelte']},
  {'user_id': 1767, 'user_stacks': ['Blazor', 'Node.js', 'Svelte', 'C#', 'Angular']},
  {'user_id': 1768, 'user_stacks': ['.NET', 'ASP.NET', 'HTML/CSS']},
  {'user_id': 1769, 'user_stacks': ['PyTorch', 'Keras', 'Swift', 'SwiftUI', 'R', 'C++', 'Django', 'Ruby']},
  {'user_id': 1770, 'user_stacks': ['Electron', 'Vue.js', 'React Native', 'React', 'Django', 'Opencv', 'RabbitMQ', 'AngularJS', 'C#']},
  {'user_id': 1771, 'user_stacks': ['Torch']},
  {'user_id': 1772, 'user_stacks': ['Ruby on Rails', 'NestJS', 'Go']},
  {'user_id': 1773, 'user_stacks': ['Next.js', 'OpenGL', 'Blazor', 'Apache Spark', 'ASP.NET', 'Ruby on Rails', 'SwiftUI', 'Swift', 'Flutter', '.NET']},
  {'user_id': 1774, 'user_stacks': ['Torch', 'Ruby', 'Qt', 'Pandas', 'Laravel', 'Electron', 'Python', 'C', 'AngularJS', 'SpringBoot']},
  {'user_id': 1775, 'user_stacks': ['NestJS', 'Django']},
  {'user_id': 1776, 'user_stacks': ['Svelte']},
  {'user_id': 1777, 'user_stacks': ['Next.js', 'Keras', 'PyTorch', 'Swift', 'Ruby on Rails']},
  {'user_id': 1778, 'user_stacks': ['TypeScript']},
  {'user_id': 1779, 'user_stacks': ['Electron', 'Swift', 'scikit-Learn', 'JavaScript', 'Torch', 'SpringBoot', 'Django', 'Next.js']},
  {'user_id': 1780, 'user_stacks': ['Java', 'Apache Spark', 'HTML/CSS', 'Laravel', 'Svelte', 'Lua']},
  {'user_id': 1781, 'user_stacks': ['Java', 'jQuery', 'Laravel']},
  {'user_id': 1782, 'user_stacks': ['Swift', 'Electron', 'OpenGL', 'AngularJS', 'React Native', 'Svelte', 'RabbitMQ']},
  {'user_id': 1783, 'user_stacks': ['Lua', 'React Native', 'Flask']},
  {'user_id': 1784, 'user_stacks': ['Opencv', 'scikit-Learn', 'SpringBoot', 'Apache Spark', '.NET', 'Next.js']},
  {'user_id': 1785, 'user_stacks': ['Go', 'C++', 'JavaScript', 'Ruby on Rails', 'C']},
  {'user_id': 1786, 'user_stacks': ['Electron', 'TensorFlow', '.NET', 'PHP', 'SwiftUI']},
  {'user_id': 1787, 'user_stacks': ['Rust', 'TypeScript', 'Qt', 'Python', 'React', 'SpringBoot', 'Node.js', 'Blazor']},
  {'user_id': 1788, 'user_stacks': ['Svelte', 'Django', 'AngularJS', 'Flutter', 'Blazor', 'Express', 'SwiftUI', 'OpenGL']},
  {'user_id': 1789, 'user_stacks': ['Kotlin', 'Laravel', 'C#', 'TypeScript', 'SpringBoot', 'React Native']},
  {'user_id': 1790, 'user_stacks': ['Ruby', 'RabbitMQ', 'Lua', 'Pandas', 'Blazor', 'C#', 'Go']},
  {'user_id': 1791, 'user_stacks': ['ASP.NET', 'Torch', 'Blazor', 'SwiftUI', 'NestJS', 'Python']},
  {'user_id': 1792, 'user_stacks': ['Go', 'Svelte', 'Apache Spark', 'scikit-Learn', 'ASP.NET', 'OpenGL']},
  {'user_id': 1793, 'user_stacks': ['Torch', 'scikit-Learn', 'Vue.js', 'Lua', 'Rust', 'Express', 'SwiftUI']},
  {'user_id': 1794, 'user_stacks': ['scikit-Learn']},
  {'user_id': 1795, 'user_stacks': ['SpringBoot', 'jQuery', 'React', 'SwiftUI']},
  {'user_id': 1796, 'user_stacks': ['React']},
  {'user_id': 1797, 'user_stacks': ['C#', 'Electron', 'React Native', 'Next.js', 'Dart', 'Kotlin', 'NestJS', 'TensorFlow']},
  {'user_id': 1798, 'user_stacks': ['NestJS', 'Kotlin', 'Laravel', 'Blazor', 'React', 'Lua', 'Node.js', 'Swift', 'Django']},
  {'user_id': 1799, 'user_stacks': ['JavaScript', 'Keras', 'Opencv', 'OpenGL', 'React', 'Blazor', 'PyTorch', 'AngularJS']},
  {'user_id': 1800, 'user_stacks': ['C#', 'Vue.js', 'NestJS', 'Lua', 'scikit-Learn', 'C', 'Flutter', 'Java']},
  {'user_id': 1801, 'user_stacks': ['C', 'Java', 'TensorFlow', 'Pandas', 'SpringBoot', 'Blazor', 'NestJS', 'OpenGL', 'Electron']},
  {'user_id': 1802, 'user_stacks': ['OpenGL', 'Qt', 'Electron']},
  {'user_id': 1803, 'user_stacks': ['Dart']},
  {'user_id': 1804, 'user_stacks': ['TypeScript', '.NET']},
  {'user_id': 1805, 'user_stacks': ['Opencv', 'HTML/CSS', 'JavaScript', 'Vue.js', 'scikit-Learn', 'TypeScript', 'AngularJS', 'Rust', 'Torch', 'Electron']},
  {'user_id': 1806, 'user_stacks': ['C#', 'TensorFlow', 'PyTorch', '.NET']},
  {'user_id': 1807, 'user_stacks': ['OpenGL', 'React Native', 'AngularJS', 'Python', 'Go', 'Rust', 'Java', 'scikit-Learn', 'Ruby']},
  {'user_id': 1808, 'user_stacks': ['C++', 'scikit-Learn', 'C', 'Vue.js']},
  {'user_id': 1809, 'user_stacks': ['Django', 'Pandas', 'Keras', 'Flutter', 'C++', 'Laravel', 'Node.js', 'Blazor']},
  {'user_id': 1810, 'user_stacks': ['Angular', 'jQuery']},
  {'user_id': 1811, 'user_stacks': ['Flutter', 'Ruby on Rails']},
  {'user_id': 1812, 'user_stacks': ['Lua', 'Angular']},
  {'user_id': 1813, 'user_stacks': ['Next.js', 'Apache Spark', 'Torch', 'SpringBoot', 'Svelte', 'Electron', 'TensorFlow', 'Vue.js', 'Opencv', 'Flutter']},
  {'user_id': 1814, 'user_stacks': ['HTML/CSS', 'Electron', 'Next.js', 'React Native', 'NestJS', 'Ruby on Rails', 'Qt']},
  {'user_id': 1815, 'user_stacks': ['SwiftUI', 'OpenGL', 'Vue.js', 'jQuery', 'Rust', 'Blazor', 'R']},
  {'user_id': 1816, 'user_stacks': ['React Native', 'Python', 'Express', 'PyTorch', 'C', 'Swift', 'Laravel', 'React', 'Apache Spark', 'TypeScript']},
  {'user_id': 1817, 'user_stacks': ['Torch', 'Angular', 'Electron', 'Pandas', 'Swift']},
  {'user_id': 1818, 'user_stacks': ['Lua', 'Express', 'Apache Spark', 'Node.js', 'TypeScript']},
  {'user_id': 1819, 'user_stacks': ['SpringBoot', 'Electron', 'Svelte', 'RabbitMQ', 'Lua', 'ASP.NET', 'Flutter', 'C', 'PyTorch']},
  {'user_id': 1820, 'user_stacks': ['Flutter']},
  {'user_id': 1821, 'user_stacks': ['Ruby', 'Express', 'React', 'SwiftUI', 'Django', 'Blazor', 'Laravel']},
  {'user_id': 1822, 'user_stacks': ['Express', 'ASP.NET', 'JavaScript', 'Swift', 'Svelte', 'Flutter']},
  {'user_id': 1823, 'user_stacks': ['Blazor', 'R', 'scikit-Learn']},
  {'user_id': 1824, 'user_stacks': ['C#']},
  {'user_id': 1825, 'user_stacks': ['C', 'Keras', 'HTML/CSS', 'SwiftUI', 'Go', 'TypeScript', 'Ruby', 'TensorFlow', 'Laravel', 'Qt']},
  {'user_id': 1826, 'user_stacks': ['Vue.js', 'Apache Spark', 'Dart', 'React Native', 'Rust', 'Lua']},
  {'user_id': 1827, 'user_stacks': ['TensorFlow', 'ASP.NET', 'Keras', 'Blazor', 'R', 'HTML/CSS', 'Java']},
  {'user_id': 1828, 'user_stacks': ['Keras', 'RabbitMQ', 'Python', 'Ruby', 'OpenGL', 'SwiftUI']},
  {'user_id': 1829, 'user_stacks': ['scikit-Learn', 'Dart', 'C++', '.NET']},
  {'user_id': 1830, 'user_stacks': ['Apache Spark', 'TensorFlow', 'React']},
  {'user_id': 1831, 'user_stacks': ['HTML/CSS', 'Python', 'scikit-Learn', 'Java', 'TypeScript', 'SpringBoot']},
  {'user_id': 1832, 'user_stacks': ['Rust']},
  {'user_id': 1833, 'user_stacks': ['Torch', 'C', 'React']},
  {'user_id': 1834, 'user_stacks': ['Dart', 'OpenGL', 'TensorFlow', 'Svelte', 'NestJS']},
  {'user_id': 1835, 'user_stacks': ['React', 'SpringBoot']},
  {'user_id': 1836, 'user_stacks': ['Svelte', 'Keras', 'Blazor', 'SpringBoot', 'HTML/CSS', 'Node.js', 'NestJS', 'Java', 'AngularJS']},
  {'user_id': 1837, 'user_stacks': ['Keras', 'Express', 'C++', 'Flutter', 'Next.js', 'PyTorch', 'HTML/CSS']},
  {'user_id': 1838, 'user_stacks': ['Ruby', 'Express', 'AngularJS']},
  {'user_id': 1839, 'user_stacks': ['Python', 'Express', 'Apache Spark', 'TensorFlow', 'SpringBoot', 'Kotlin', 'Flutter']},
  {'user_id': 1840, 'user_stacks': ['PHP', 'C', 'Flask', 'Blazor', 'Node.js', 'Opencv']},
  {'user_id': 1841, 'user_stacks': ['Blazor', 'Vue.js', 'Angular']},
  {'user_id': 1842, 'user_stacks': ['Flask', 'SpringBoot', 'React', 'Opencv', 'Blazor', 'PHP', 'ASP.NET', 'Node.js']},
  {'user_id': 1843, 'user_stacks': ['Angular']},
  {'user_id': 1844, 'user_stacks': ['Python', 'Apache Spark']},
  {'user_id': 1845, 'user_stacks': ['AngularJS', 'R', 'HTML/CSS', 'PHP', 'Django', 'Node.js', 'C++', 'Express']},
  {'user_id': 1846, 'user_stacks': ['HTML/CSS', 'Python', 'Flask', 'Opencv', 'C']},
  {'user_id': 1847, 'user_stacks': ['Ruby', 'Torch', 'JavaScript', 'Pandas', 'Dart', 'Java', 'Node.js', 'PHP']},
  {'user_id': 1848, 'user_stacks': ['Swift', 'Rust', 'Keras', 'Opencv']},
  {'user_id': 1849, 'user_stacks': ['Dart', 'React Native', 'AngularJS', 'TypeScript', 'Apache Spark', 'Python', 'SpringBoot', 'jQuery', 'Flask']},
  {'user_id': 1850, 'user_stacks': ['.NET', 'Express', 'R', 'Keras', 'Rust', 'Qt', 'Node.js', 'Vue.js', 'TypeScript']},
  {'user_id': 1851, 'user_stacks': ['Ruby on Rails', 'Torch']},
  {'user_id': 1852, 'user_stacks': ['TypeScript', 'Ruby on Rails', 'Express', 'Vue.js', 'JavaScript', 'Laravel', 'Pandas', 'ASP.NET', 'React Native']},
  {'user_id': 1853, 'user_stacks': ['Go', 'Laravel', 'Torch', 'SwiftUI', 'scikit-Learn', 'RabbitMQ']},
  {'user_id': 1854, 'user_stacks': ['HTML/CSS', 'Angular', 'Ruby', 'SwiftUI', 'C#', 'ASP.NET', 'Django', 'Python']},
  {'user_id': 1855, 'user_stacks': ['Django', 'R', 'Apache Spark', 'NestJS', 'Qt', 'ASP.NET', 'Lua']},
  {'user_id': 1856, 'user_stacks': ['Next.js', 'Django', 'Ruby', 'Qt', 'Apache Spark', 'JavaScript', 'jQuery', 'Flask', 'Lua', 'SwiftUI']},
  {'user_id': 1857, 'user_stacks': ['SpringBoot', 'Vue.js', 'Opencv', 'Torch']},
  {'user_id': 1858, 'user_stacks': ['Keras', 'Lua', 'React Native', 'OpenGL', 'Electron', 'Node.js', 'Go', 'Kotlin', 'Laravel', 'HTML/CSS']},
  {'user_id': 1859, 'user_stacks': ['Swift']},
  {'user_id': 1860, 'user_stacks': ['Express', 'Node.js']},
  {'user_id': 1861, 'user_stacks': ['Vue.js', 'scikit-Learn', 'Ruby on Rails', 'Qt', 'Flutter', 'Keras', 'Node.js', 'Angular', 'C', 'AngularJS']},
  {'user_id': 1862, 'user_stacks': ['Apache Spark', 'RabbitMQ', 'React', 'Flutter', 'C#', 'TensorFlow', 'Lua']},
  {'user_id': 1863, 'user_stacks': ['Qt', 'jQuery', 'ASP.NET', 'SpringBoot', 'Blazor', 'Pandas', 'HTML/CSS', 'C', 'Flutter']},
  {'user_id': 1864, 'user_stacks': ['C#', 'Vue.js', 'Kotlin', 'Torch', 'Swift', 'Flask', 'Electron']},
  {'user_id': 1865, 'user_stacks': ['R', 'C', 'C++', 'Lua']},
  {'user_id': 1866, 'user_stacks': ['C++']},
  {'user_id': 1867, 'user_stacks': ['Django', 'Java', 'TypeScript', 'Angular', 'SwiftUI', 'Apache Spark', 'TensorFlow', 'Flask']},
  {'user_id': 1868, 'user_stacks': ['C', 'AngularJS', '.NET', 'Qt', 'Angular', 'SwiftUI', 'Next.js', 'PHP', 'R']},
  {'user_id': 1869, 'user_stacks': ['Torch', 'Angular', 'HTML/CSS', 'Java', 'Svelte', 'Keras', 'C', 'Laravel']},
  {'user_id': 1870, 'user_stacks': ['JavaScript', 'Svelte']},
  {'user_id': 1871, 'user_stacks': ['Dart']},
  {'user_id': 1872, 'user_stacks': ['R', 'Python', 'Go', 'Opencv', 'Rust', 'RabbitMQ']},
  {'user_id': 1873, 'user_stacks': ['scikit-Learn', 'Blazor', 'PHP']},
  {'user_id': 1874, 'user_stacks': ['SpringBoot']},
  {'user_id': 1875, 'user_stacks': ['React Native', 'Next.js', 'TensorFlow']},
  {'user_id': 1876, 'user_stacks': ['React', 'Dart', 'JavaScript', 'Java', 'SpringBoot', 'jQuery', 'Svelte', 'R', 'RabbitMQ']},
  {'user_id': 1877, 'user_stacks': ['C++']},
  {'user_id': 1878, 'user_stacks': ['OpenGL', 'Swift', 'Python']},
  {'user_id': 1879, 'user_stacks': ['Opencv', 'Blazor', 'Rust', 'scikit-Learn', 'R', 'Angular']},
  {'user_id': 1880, 'user_stacks': ['Go', 'SwiftUI']},
  {'user_id': 1881, 'user_stacks': ['jQuery', 'C++', 'Next.js', 'Apache Spark', 'Kotlin', 'Express', 'OpenGL', 'Dart', 'Electron']},
  {'user_id': 1882, 'user_stacks': ['Qt', 'Python', '.NET', 'Go', 'Pandas']},
  {'user_id': 1883, 'user_stacks': ['HTML/CSS', 'Node.js', 'Opencv', 'C', 'Apache Spark']},
  {'user_id': 1884, 'user_stacks': ['PHP', 'R']},
  {'user_id': 1885, 'user_stacks': ['Node.js', 'Ruby', 'Opencv']},
  {'user_id': 1886, 'user_stacks': ['Flask', 'NestJS', 'OpenGL', 'Qt', 'Dart', 'Rust']},
  {'user_id': 1887, 'user_stacks': ['Dart', 'OpenGL', 'Java', 'HTML/CSS', 'Torch', 'jQuery']},
  {'user_id': 1888, 'user_stacks': ['JavaScript', 'Qt', 'Python', 'Blazor', 'Flutter']},
  {'user_id': 1889, 'user_stacks': ['Pandas', 'Blazor', 'JavaScript', 'HTML/CSS']},
  {'user_id': 1890, 'user_stacks': ['SwiftUI', 'Rust', 'Keras', 'PHP']},
  {'user_id': 1891, 'user_stacks': ['SpringBoot', 'Vue.js', 'Lua', 'Express', 'TypeScript', 'Python', 'Rust', 'Next.js', 'Ruby on Rails', 'AngularJS']},
  {'user_id': 1892, 'user_stacks': ['SpringBoot', 'Python', 'NestJS', 'scikit-Learn', 'PHP', 'Next.js', 'Ruby on Rails', 'C++']},
  {'user_id': 1893, 'user_stacks': ['Django']},
  {'user_id': 1894, 'user_stacks': ['.NET', 'Electron', 'React Native']},
  {'user_id': 1895, 'user_stacks': ['RabbitMQ', 'OpenGL', 'Electron', 'TensorFlow', 'C++', 'PyTorch', 'Python', 'Dart']},
  {'user_id': 1896, 'user_stacks': ['Swift', 'Ruby on Rails', 'Express', 'PHP', 'Vue.js', 'Opencv', 'Node.js', 'Electron', 'TensorFlow']},
  {'user_id': 1897, 'user_stacks': ['Angular', 'Qt', 'R']},
  {'user_id': 1898, 'user_stacks': ['Swift', 'jQuery', 'Pandas', 'Ruby', '.NET', 'React Native', 'Svelte']},
  {'user_id': 1899, 'user_stacks': ['Next.js', 'Swift', 'TypeScript', 'Keras', 'C#', 'scikit-Learn', '.NET', 'Electron']},
  {'user_id': 1900, 'user_stacks': ['Torch', 'SwiftUI', '.NET']},
  {'user_id': 1901, 'user_stacks': ['Pandas', 'Dart', 'Apache Spark', 'Django', 'Next.js', 'SwiftUI', 'Rust', 'Lua']},
  {'user_id': 1902, 'user_stacks': ['Flask']},
  {'user_id': 1903, 'user_stacks': ['Vue.js', 'Java', 'Keras', 'JavaScript', 'Next.js', 'Flask', 'R']},
  {'user_id': 1904, 'user_stacks': ['Keras', 'PyTorch', 'React Native', 'Electron', 'Angular']},
  {'user_id': 1905, 'user_stacks': ['HTML/CSS', 'ASP.NET', 'Qt', 'Ruby', 'Python', 'Ruby on Rails', 'Flutter', 'PHP']},
  {'user_id': 1906, 'user_stacks': ['RabbitMQ', 'Qt', 'Ruby']},
  {'user_id': 1907, 'user_stacks': ['Kotlin']},
  {'user_id': 1908, 'user_stacks': ['PHP', 'Ruby', 'Laravel', 'Keras']},
  {'user_id': 1909, 'user_stacks': ['Swift', 'OpenGL', 'AngularJS', 'R']},
  {'user_id': 1910, 'user_stacks': ['Django', 'ASP.NET', 'NestJS', 'Next.js', 'C', 'Go']},
  {'user_id': 1911, 'user_stacks': ['C#', 'Django', 'Ruby on Rails', '.NET', 'Flutter', 'Laravel', 'Electron', 'C', 'SwiftUI', 'TensorFlow']},
  {'user_id': 1912, 'user_stacks': ['R', 'Blazor', 'Flask', 'HTML/CSS', 'Svelte', 'Qt', 'Go', 'Keras', 'SwiftUI']},
  {'user_id': 1913, 'user_stacks': ['Flask', 'TypeScript', 'Ruby on Rails', 'Express', 'Kotlin', 'Blazor', 'RabbitMQ', 'Lua', 'C++', 'HTML/CSS']},
  {'user_id': 1914, 'user_stacks': ['PyTorch', 'Node.js', 'scikit-Learn', 'Flutter', 'Django', 'Flask', 'OpenGL', 'JavaScript']},
  {'user_id': 1915, 'user_stacks': ['SwiftUI', 'Pandas']},
  {'user_id': 1916, 'user_stacks': ['Next.js', 'Vue.js', 'PyTorch', 'Go', 'ASP.NET', 'Flutter', 'Java', 'Kotlin', 'C']},
  {'user_id': 1917, 'user_stacks': ['C#', 'TensorFlow', 'Svelte', 'Swift', 'Opencv']},
  {'user_id': 1918, 'user_stacks': ['Python', 'Electron']},
  {'user_id': 1919, 'user_stacks': ['Keras', 'Electron']},
  {'user_id': 1920, 'user_stacks': ['Electron', 'Python']},
  {'user_id': 1921, 'user_stacks': ['ASP.NET', 'Go', 'Swift', 'Opencv', 'Java', 'JavaScript', 'scikit-Learn']},
  {'user_id': 1922, 'user_stacks': ['Angular', 'Electron', 'Keras', 'SpringBoot']},
  {'user_id': 1923, 'user_stacks': ['SwiftUI', 'TypeScript', 'Electron', 'Next.js', 'scikit-Learn', 'Blazor', 'Django', 'Ruby', 'HTML/CSS']},
  {'user_id': 1924, 'user_stacks': ['Pandas', 'SwiftUI', 'Lua', 'Svelte', 'Express', 'React Native', 'Opencv']},
  {'user_id': 1925, 'user_stacks': ['Swift', 'Ruby', 'Express', 'Flutter', 'OpenGL', 'Keras', 'Opencv']},
  {'user_id': 1926, 'user_stacks': ['Opencv', 'NestJS', 'Pandas', 'Flask', 'Flutter']},
  {'user_id': 1927, 'user_stacks': ['scikit-Learn', 'C++', 'Qt', 'PHP']},
  {'user_id': 1928, 'user_stacks': ['PyTorch', 'Lua', 'React']},
  {'user_id': 1929, 'user_stacks': ['Angular', 'TypeScript', 'Dart', 'Python', 'Node.js', 'Vue.js', 'Laravel', 'React', 'Apache Spark', 'TensorFlow']},
  {'user_id': 1930, 'user_stacks': ['Laravel', 'C#']},
  {'user_id': 1931, 'user_stacks': ['Kotlin', 'Apache Spark', 'Vue.js', 'JavaScript', 'TypeScript']},
  {'user_id': 1932, 'user_stacks': ['React Native', 'Node.js', 'C#', 'SpringBoot', 'Java', 'scikit-Learn', 'React']},
  {'user_id': 1933, 'user_stacks': ['SpringBoot', 'OpenGL', 'Ruby on Rails', 'C', 'Swift', 'Express', 'Ruby', 'Node.js']},
  {'user_id': 1934, 'user_stacks': ['Java']},
  {'user_id': 1935, 'user_stacks': ['SpringBoot', 'Swift', 'Opencv', 'OpenGL', 'TypeScript', 'Laravel', 'R', 'Vue.js', 'Python']},
  {'user_id': 1936, 'user_stacks': ['Ruby', 'Flask', 'TypeScript', 'Swift', 'Qt', 'C', 'Angular']},
  {'user_id': 1937, 'user_stacks': ['TensorFlow', 'Ruby on Rails', 'PyTorch', 'Python', 'Django', 'Electron', 'React']},
  {'user_id': 1938, 'user_stacks': ['Vue.js', 'Apache Spark', 'ASP.NET', 'Rust', 'Electron', 'React', 'Go', 'Lua']},
  {'user_id': 1939, 'user_stacks': ['Go', 'Flask', 'Lua', 'ASP.NET', 'Laravel', 'Next.js', 'R', 'PHP']},
  {'user_id': 1940, 'user_stacks': ['Qt', 'Swift', 'Flask', 'Apache Spark', 'PHP', 'Electron', 'Kotlin', 'Laravel', 'C']},
  {'user_id': 1941, 'user_stacks': ['Rust', 'Keras', 'Django', 'Swift', '.NET', 'jQuery', 'Java', 'C#', 'Ruby on Rails']},
  {'user_id': 1942, 'user_stacks': ['Svelte', 'R', 'Torch', 'React', 'Go']},
  {'user_id': 1943, 'user_stacks': ['Python', 'SwiftUI']},
  {'user_id': 1944, 'user_stacks': ['PHP', 'Rust', 'Node.js', 'C#', 'Python', 'React', 'AngularJS', 'Svelte', 'Opencv']},
  {'user_id': 1945, 'user_stacks': ['Keras', 'SpringBoot', 'Blazor', 'React Native', 'ASP.NET', 'C#', 'TensorFlow', 'Java', 'scikit-Learn']},
  {'user_id': 1946, 'user_stacks': ['ASP.NET', 'AngularJS', 'HTML/CSS', 'Laravel', 'Python', 'Rust', 'Electron', 'scikit-Learn', 'NestJS', 'Pandas']},
  {'user_id': 1947, 'user_stacks': ['Rust', 'Qt']},
  {'user_id': 1948, 'user_stacks': ['C', 'Django', 'C#']},
  {'user_id': 1949, 'user_stacks': ['Python', 'Flutter', 'Ruby', 'AngularJS', 'Blazor', 'Java', 'C++', 'NestJS', 'Django', 'Node.js']},
  {'user_id': 1950, 'user_stacks': ['Vue.js', 'Ruby']},
  {'user_id': 1951, 'user_stacks': ['Django', 'SpringBoot', 'jQuery', 'Flask']},
  {'user_id': 1952, 'user_stacks': ['Apache Spark', 'Flask', 'Go', 'R']},
  {'user_id': 1953, 'user_stacks': ['Next.js', 'Go', 'Dart', 'React Native', 'Java', 'Qt', 'Swift', 'Kotlin']},
  {'user_id': 1954, 'user_stacks': ['Rust', 'Django']},
  {'user_id': 1955, 'user_stacks': ['C++', 'Vue.js', 'Angular', 'Kotlin', 'React', 'Java', 'Flutter', 'Next.js']},
  {'user_id': 1956, 'user_stacks': ['Django', 'Svelte', 'Laravel', 'Pandas', 'scikit-Learn', 'Flask', 'Torch', 'R', 'HTML/CSS']},
  {'user_id': 1957, 'user_stacks': ['React', 'Node.js', 'Java']},
  {'user_id': 1958, 'user_stacks': ['Vue.js', 'Express', 'PHP', 'Go', 'Flutter', 'Rust', 'Lua', 'Ruby on Rails', 'React', 'Keras']},
  {'user_id': 1959, 'user_stacks': ['Flask', 'Keras', 'Kotlin', 'ASP.NET', 'NestJS', 'SwiftUI']},
  {'user_id': 1960, 'user_stacks': ['React Native', 'Next.js', 'Swift', 'Electron', 'PHP', 'Node.js', 'Blazor']},
  {'user_id': 1961, 'user_stacks': ['Lua', 'Flask', 'PHP', 'R', 'Python', 'Laravel', 'SpringBoot']},
  {'user_id': 1962, 'user_stacks': ['Apache Spark', 'C#', 'SwiftUI', 'Flask', 'scikit-Learn', 'Vue.js', 'C', 'Electron', 'Laravel', 'JavaScript']},
  {'user_id': 1963, 'user_stacks': ['Electron', 'C++']},
  {'user_id': 1964, 'user_stacks': ['Kotlin', 'Pandas', 'Ruby on Rails', 'AngularJS', 'SpringBoot', '.NET', 'Angular', 'C++', 'Python', 'Django']},
  {'user_id': 1965, 'user_stacks': ['RabbitMQ', 'TypeScript', 'Django', 'C++', 'Next.js', 'Pandas', 'Opencv', 'Rust', 'Qt', 'Lua']},
  {'user_id': 1966, 'user_stacks': ['TensorFlow', 'TypeScript', 'Pandas', 'Node.js', 'Ruby', 'Torch']},
  {'user_id': 1967, 'user_stacks': ['C++', 'TypeScript', 'C#']},
  {'user_id': 1968, 'user_stacks': ['Laravel', 'ASP.NET', 'Swift', 'Keras', 'Opencv', 'React Native', 'PyTorch', 'HTML/CSS']},
  {'user_id': 1969, 'user_stacks': ['Lua', 'R', 'Rust', 'SpringBoot', 'SwiftUI', 'jQuery', 'HTML/CSS', 'Python']},
  {'user_id': 1970, 'user_stacks': ['Next.js', 'Blazor', 'Node.js', 'Java']},
  {'user_id': 1971, 'user_stacks': ['React Native', 'RabbitMQ', 'C#', 'Qt', 'Swift', 'Apache Spark', 'jQuery', 'Blazor', '.NET', 'Kotlin']},
  {'user_id': 1972, 'user_stacks': ['OpenGL', 'Ruby on Rails', 'Swift', 'Java', 'Keras', 'Flask', 'Electron', 'Angular']},
  {'user_id': 1973, 'user_stacks': ['Django', 'scikit-Learn', 'Pandas', 'React', 'JavaScript', 'AngularJS', 'RabbitMQ', 'Opencv', 'OpenGL', 'TensorFlow']},
  {'user_id': 1974, 'user_stacks': ['Opencv', 'React Native', 'Next.js', 'Svelte', 'PyTorch', 'NestJS']},
  {'user_id': 1975, 'user_stacks': ['jQuery', 'NestJS', 'Kotlin', '.NET']},
  {'user_id': 1976, 'user_stacks': ['OpenGL', 'Flutter', 'TypeScript', 'ASP.NET', 'Next.js', 'Node.js']},
  {'user_id': 1977, 'user_stacks': ['Python', 'Node.js', 'Kotlin', 'C#', 'Torch']},
  {'user_id': 1978, 'user_stacks': ['C#']},
  {'user_id': 1979, 'user_stacks': ['Angular']},
  {'user_id': 1980, 'user_stacks': ['TypeScript', 'Angular', 'Django', 'scikit-Learn', 'Blazor']},
  {'user_id': 1981, 'user_stacks': ['jQuery', 'HTML/CSS', 'Vue.js', 'Python', '.NET', 'Lua', 'Go', 'React Native', 'Apache Spark']},
  {'user_id': 1982, 'user_stacks': ['Rust', 'ASP.NET', 'NestJS', 'Laravel', 'Node.js', 'C#', 'jQuery', 'SpringBoot', 'AngularJS']},
  {'user_id': 1983, 'user_stacks': ['Flutter', 'Swift', 'Go']},
  {'user_id': 1984, 'user_stacks': ['SwiftUI', 'Svelte', 'Keras', 'Lua', '.NET', 'Vue.js', 'React Native']},
  {'user_id': 1985, 'user_stacks': ['Next.js', 'Node.js', 'C#', 'Dart', 'JavaScript', 'Pandas', 'Blazor', 'Ruby', 'Svelte', 'Keras']},
  {'user_id': 1986, 'user_stacks': ['Angular', 'Ruby on Rails', 'C++', 'SpringBoot', 'Svelte']},
  {'user_id': 1987, 'user_stacks': ['Express', 'HTML/CSS', 'jQuery', 'Laravel', 'Torch']},
  {'user_id': 1988, 'user_stacks': ['Kotlin', 'Ruby', 'R', 'jQuery', 'RabbitMQ', 'Qt']},
  {'user_id': 1989, 'user_stacks': ['R']},
  {'user_id': 1990, 'user_stacks': ['Java', 'Laravel', 'SpringBoot', 'Next.js', 'Node.js']},
  {'user_id': 1991, 'user_stacks': ['OpenGL']},
  {'user_id': 1992, 'user_stacks': ['Vue.js', 'PHP', '.NET', 'React']},
  {'user_id': 1993, 'user_stacks': ['Opencv', 'SwiftUI', 'RabbitMQ', 'React', 'Vue.js', 'Django', 'TensorFlow', 'scikit-Learn', '.NET', 'Svelte']},
  {'user_id': 1994, 'user_stacks': ['ASP.NET', 'AngularJS', 'C']},
  {'user_id': 1995, 'user_stacks': ['Qt', 'AngularJS', 'Rust', '.NET']},
  {'user_id': 1996, 'user_stacks': ['RabbitMQ', 'scikit-Learn', 'PyTorch', 'Vue.js', 'React Native']},
  {'user_id': 1997, 'user_stacks': ['C++', 'PHP', 'Blazor', 'C', '.NET', 'Kotlin']},
  {'user_id': 1998, 'user_stacks': ['Pandas', 'Flutter', 'Opencv', 'C++', 'Angular', 'Rust', 'SwiftUI', 'R', 'SpringBoot']},
];


