###프로젝트 생성 ok
POST http://localhost:8000/project/create
Accept: application/json
Content-Type: application/json

{
  "project_title": "prj4",
  "project_content": "content4",
  "list_count": 7,
  "visited_number": 12,
  "project_type": "앱",
  "project_start_date": "2023-06-19",
  "project_end_date": "2023-09-19",
  "location": 1,
  "is_available": "VALID",
  "project_stacks": [
    {
      "project": null,
      "development_stack": "웹 프론트엔드",
      "require_member": 1,
      "require_grade": 2
    },
    {
      "project": null,
      "development_stack": "웹 백엔드",
      "require_member": 1,
      "require_grade": 3
    }
  ]
}

### 프로젝트 리스트 테스트 완료.
GET http://localhost:8000/project/list
Accept: application/json
Content-Type: application/json

### 프로젝트 상세보기 (미완성)
GET http://localhost:8000/project/details?project_id=10
Accept: application/json
Content-Type: application/json



### 지원하기
POST http://localhost:8000/project/apply
Accept: application/json
Content-Type: application/json

{
  "id":"id5678",
  "project_id": 17
}

