spring:
  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/teaming?useSSL=false&serverTimezone=Asia/Seoul
#    username: sumin
#    password: 9030
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://teaming.cljwrswc5o75.ap-northeast-2.rds.amazonaws.com:3306/teaming?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: admin
    password: 12345678
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: true
  jpa:
    hibernate:
      ddl-auto: create
    generate-ddl: false
    show-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  main:
    allow-bean-definition-overriding: true
  mvc:
    converters:
      preferred-json-mapper: jackson

server:
  port: 8000


logging:
  level:
    org:
      hibernate: info